#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
#python manage.py runserver 0.0.0.0:8000  --nothreading --noreload -v 3
uvicorn config.asgi:application --host 0.0.0.0 --reload --loop 'uvloop' --http 'httptools' --no-access-log
