from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

urlpatterns = (
    path("Subject/", views.SubjectListView.as_view(), name="repository_Subject_list"),
    path("Subject/create/", views.SubjectCreateView.as_view(), name="repository_Subject_create"),
    path("Subject/detail/<int:pk>/", views.SubjectDetailView.as_view(), name="repository_Subject_detail"),
    path("Subject/update/<int:pk>/", views.SubjectUpdateView.as_view(), name="repository_Subject_update"),
    path("Organization/", views.OrganizationListView.as_view(), name="repository_Organization_list"),
    path("Organization/create/", views.OrganizationCreateView.as_view(), name="repository_Organization_create"),
    path("Organization/detail/<int:pk>/", views.OrganizationDetailView.as_view(),
         name="repository_Organization_detail"),
    path("Organization/update/<int:pk>/", views.OrganizationUpdateView.as_view(),
         name="repository_Organization_update"),
    path("EduProgram/", views.EduProgramListView.as_view(), name="repository_EduProgram_list"),
    path("EduProgram/create/", views.EduProgramCreateView.as_view(), name="repository_EduProgram_create"),
    path("EduProgram/detail/<int:pk>/", views.EduProgramDetailView.as_view(), name="repository_EduProgram_detail"),
    path("EduProgram/update/<int:pk>/", views.EduProgramUpdateView.as_view(), name="repository_EduProgram_update"),
    path("ResultEdu/", views.ResultEduListView.as_view(), name="repository_ResultEdu_list"),
    path("ResultEdu/create/", views.ResultEduCreateView.as_view(), name="repository_ResultEdu_create"),
    path("ResultEdu/detail/<int:pk>/", views.ResultEduDetailView.as_view(), name="repository_ResultEdu_detail"),
    path("ResultEdu/update/<int:pk>/", views.ResultEduUpdateView.as_view(), name="repository_ResultEdu_update"),
    path("DigitalResource/", views.DigitalResourceListView.as_view(), name="repository_digitalresource_list"),
    path("DigitalResource/create/", views.DigitalResourceCreateView.as_view(),
         name="repository_DigitalResource_create"),
    path("DigitalResource/detail/<uuid:pk>/", views.DigitalResourceDetailView.as_view(),
         name="repository_DigitalResource_detail"),
    path("DigitalResource/update/<uuid:pk>/", views.DigitalResourceUpdateView.as_view(),
         name="repository_DigitalResource_update"),
    path("Competence/", views.CompetenceListView.as_view(), name="repository_Competence_list"),
    path("Competence/create/", views.CompetenceCreateView.as_view(), name="repository_Competence_create"),
    path("Competence/detail/<int:pk>/", views.CompetenceDetailView.as_view(), name="repository_Competence_detail"),
    path("Competence/update/<int:pk>/", views.CompetenceUpdateView.as_view(), name="repository_Competence_update"),
    path("Platform/", views.PlatformListView.as_view(), name="repository_Platform_list"),
    path("Platform/create/", views.PlatformCreateView.as_view(), name="repository_Platform_create"),
    path("Platform/detail/<uuid:pk>/", views.PlatformDetailView.as_view(), name="repository_Platform_detail"),
    path("Platform/update/<uuid:pk>/", views.PlatformUpdateView.as_view(), name="repository_Platform_update"),
    path("Language/", views.LanguageListView.as_view(), name="repository_Language_list"),
    path("Language/create/", views.LanguageCreateView.as_view(), name="repository_Language_create"),
    path("Language/detail/<int:pk>/", views.LanguageDetailView.as_view(), name="repository_Language_detail"),
    path("Language/update/<int:pk>/", views.LanguageUpdateView.as_view(), name="repository_Language_update"),
    path("SubjectTag/", views.SubjectTagListView.as_view(), name="repository_SubjectTag_list"),
    path("SubjectTag/create/", views.SubjectTagCreateView.as_view(), name="repository_SubjectTag_create"),
    path("SubjectTag/detail/<int:pk>/", views.SubjectTagDetailView.as_view(), name="repository_SubjectTag_detail"),
    path("SubjectTag/update/<int:pk>/", views.SubjectTagUpdateView.as_view(), name="repository_SubjectTag_update"),
    path("EduProgramTag/", views.EduProgramTagListView.as_view(), name="repository_EduProgramTag_list"),
    path("EduProgramTag/create/", views.EduProgramTagCreateView.as_view(), name="repository_EduProgramTag_create"),
    path("EduProgramTag/detail/<int:pk>/", views.EduProgramTagDetailView.as_view(),
         name="repository_EduProgramTag_detail"),
    path("EduProgramTag/update/<int:pk>/", views.EduProgramTagUpdateView.as_view(),
         name="repository_EduProgramTag_update"),
    path("DigitalResource/my/", views.ResourceListView.as_view(), name="repository_digitalresource_owner_list"),
    # path("search/", views.ResourceListView.as_view(), name="repository_Search"), # TODO: поиск ЭОР
    path("statistics/", views.statistics, name="repository_statistics"),
    path("resource/<uuid:pk>/bookmark/", login_required(views.BookmarkView.as_view()), name='resource_bookmark'),
    path("DigitalResource/favorite/", views.DigitalResourceBookmarkListView.as_view(),
         name="repository_digitalresource_list_fav"),
)
