# Generated by Django 3.1.4 on 2021-03-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('survey', '0014_auto_20210323_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
