# Generated by Django 3.1.12 on 2021-08-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_auto_20210822_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='indicator',
        ),
    ]
