# Generated by Django 3.2.6 on 2021-09-16 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0021_auto_20210907_1444'),
        ('survey', '0021_answer_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.subject', verbose_name='Дисциплина'),
        ),
    ]
