# Generated by Django 3.2.16 on 2022-10-26 02:20

import auto_prefetch
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0023_question_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('survey', 'order'), 'verbose_name': 'показатель', 'verbose_name_plural': 'показатели'},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'get_latest_by': 'created', 'verbose_name': 'показатель заключения', 'verbose_name_plural': 'показатели заключения'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'вид экспертизы', 'verbose_name_plural': 'виды экспертизы'},
        ),
        migrations.RemoveField(
            model_name='response',
            name='expertise_request',
        ),
        migrations.AddField(
            model_name='response',
            name='expertise_opinion',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='inspections.expertiseopinion', verbose_name='Экспертное заключение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='survey',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='survey.survey', verbose_name='Вид экспертизы'),
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.survey', verbose_name='Вид экспертизы'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Наименование показателя'),
        ),
        migrations.AlterField(
            model_name='response',
            name='survey',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.survey', verbose_name='Вид экспертизы'),
        ),
    ]
