version: '3'

networks:
  lrr:

services:
  django: &django
    build:
      context: .
      dockerfile: compose/production.urfu/django/Dockerfile
    image: ${COMPOSE_PROJECT_NAME}_django_${ENVIRONMENT}
    container_name: ${COMPOSE_PROJECT_NAME}_django_${ENVIRONMENT}
    depends_on:
      - postgres
      - redis
    networks:
      - lrr
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    volumes:
      - ${WEB_APP_PATH}/uploads:/app/uploads
      - ${WEB_APP_PATH}/logs:/app/logs
      - ${WEB_APP_PATH}/media:/app/dp/media
      - ${WEB_APP_PATH}/gunicorn_socket/:/gunicorn_socket
    restart: unless-stopped
    command: /start

  postgres:
    build:
      context: .
      dockerfile: compose/production.urfu/postgres/Dockerfile
    image: ${COMPOSE_PROJECT_NAME}_postgres_${ENVIRONMENT}
    container_name: ${COMPOSE_PROJECT_NAME}_postgres_${ENVIRONMENT}
    networks:
      - lrr
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - ${WEB_APP_PATH}/pgdata:/var/lib/postgresql/data
      - ${WEB_APP_PATH}/backups:/backups
      - ./compose/production.urfu/postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    env_file:
      - ./.envs/.production/.postgres


  redis:
    image: redis:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_redis_${ENVIRONMENT}
    networks:
      - lrr

  celeryworker:
    <<: *django

    image: ${COMPOSE_PROJECT_NAME}_celeryworker_${ENVIRONMENT}
    container_name: ${COMPOSE_PROJECT_NAME}_celeryworker_${ENVIRONMENT}
    networks:
      - lrr
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: ${COMPOSE_PROJECT_NAME}_celerybeat_${ENVIRONMENT}
    container_name: ${COMPOSE_PROJECT_NAME}_celerybeat_${ENVIRONMENT}
    networks:
      - lrr
    command: /start-celerybeat

  # flower:
  #   <<: *django
  #   image: ${COMPOSE_PROJECT_NAME}_flower_${ENVIRONMENT}
  #   container_name: ${COMPOSE_PROJECT_NAME}_flower_${ENVIRONMENT}
  #   networks:
  #     - lrr
  #   command: /start-flower


