# Generated by Django 3.0.7 on 2020-12-22 11:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repository', '0003_auto_20201222_1642'),
        ('users', '0002_expert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('type', models.CharField(choices=[('ASYNC', 'асинхронные мероприятия'), ('SYNC', 'синхронные мероприятия')], max_length=50, null=True, verbose_name='Тип ячейки')),
                ('include_practice', models.NullBooleanField(verbose_name='Практика')),
                ('include_theory', models.NullBooleanField(verbose_name='Теория')),
                ('beg_theme_number', models.PositiveSmallIntegerField(blank=True, verbose_name='Начало диапазонов объединяемых строчек')),
                ('end_theme_number', models.PositiveSmallIntegerField(blank=True, verbose_name='Конец диапазонов объединяемых строчек')),
                ('methodology_description', models.CharField(blank=True, max_length=1024, verbose_name='Методологическое описание')),
            ],
            options={
                'verbose_name': 'Ячейка цифрового комплекса ЭУМК',
                'verbose_name_plural': 'Ячейки цифрового комплекса ЭУМК',
            },
        ),
        migrations.CreateModel(
            name='DigitalComplex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('format', models.CharField(blank=True, max_length=300, verbose_name='Формат использования')),
                ('keywords', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ключевые слова')),
                ('competences', models.ManyToManyField(blank=True, to='repository.Competence', verbose_name='Компетенции')),
                ('digital_resources', models.ManyToManyField(to='repository.DigitalResource', verbose_name='Компоненты ЭУМК')),
                ('directions', models.ManyToManyField(blank=True, to='repository.Direction', verbose_name='Направления подготовки')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='repository.Language', verbose_name='Язык комплекса')),
                ('results_edu', models.ManyToManyField(blank=True, to='repository.ResultEdu', verbose_name='Результаты обучения')),
                ('subjects', models.ManyToManyField(blank=True, to='repository.Subject', verbose_name='Дисциплина(ы)')),
            ],
            options={
                'verbose_name': 'Цифровой Комплекс (ЭУМК)',
                'verbose_name_plural': 'Цифровые Комплексы (ЭУМК)',
            },
        ),
        migrations.CreateModel(
            name='RegistryStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('experise_date', models.DateTimeField(blank=True, verbose_name='Дата экспертизы')),
                ('relevance_date', models.DateTimeField(blank=True, verbose_name='Дата обновления экспертизы')),
                ('digital_complex', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='complexes.DigitalComplex', verbose_name='Комплекс ЭМУК')),
            ],
            options={
                'verbose_name': 'Статус экспертизы комплекса',
                'verbose_name_plural': 'Статусы экспертизы комплекса',
            },
        ),
        migrations.CreateModel(
            name='WorkPlanAcademicGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('learn_date', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Учебный год')),
                ('semestr', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Семестр')),
                ('academic_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.AcademicGroup', verbose_name='Академическая группа')),
                ('digital_complex', models.ManyToManyField(to='complexes.DigitalComplex', verbose_name='Ресурсное обеспечение')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='repository.Direction', verbose_name='Направление подготовки')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='repository.Subject', verbose_name='Дисциплины')),
            ],
            options={
                'verbose_name': 'Ресурсное обеспечение академической группы',
                'verbose_name_plural': 'Ресурсное обеспечение академических групп',
            },
        ),
        migrations.CreateModel(
            name='RegistryStatusProgSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('coverage_procentage', models.PositiveSmallIntegerField(blank=True, verbose_name='Процент покрытия')),
                ('edu_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.EduProgram', verbose_name='Образовательная программа')),
                ('status', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='complexes.RegistryStatus', verbose_name='Статус экспертизы комплекса')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.Subject', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Соответсвие статуса комплекса, с дисциплинами и программами',
                'verbose_name_plural': 'Соответсвие статуса комплекса, с дисциплинами и программами',
            },
        ),
        migrations.CreateModel(
            name='ComplexTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('title', models.CharField(max_length=150, verbose_name='Наимаенование')),
                ('number', models.PositiveSmallIntegerField(blank=True, verbose_name='Номер темы')),
                ('digital_complex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complexes.DigitalComplex', verbose_name='Комплекс ЭМУК')),
            ],
            options={
                'verbose_name': 'Тема карты комплекса',
                'verbose_name_plural': 'Темы карты комплекса',
            },
        ),
        migrations.CreateModel(
            name='ComplexSpaceCell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('title', models.CharField(max_length=150, verbose_name='Наимаенование')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на образовательное пространство')),
                ('cells', models.ManyToManyField(blank=True, to='complexes.Cell', verbose_name='Ячейка комплекса')),
                ('digital_complex', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='complexes.DigitalComplex', verbose_name='Комплекс ЭМУК')),
            ],
            options={
                'verbose_name': 'Компонент ячейки комплекса',
                'verbose_name_plural': 'Компоненты ячеек комплекса',
            },
        ),
        migrations.CreateModel(
            name='CellWeeks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('beg_week_number', models.PositiveSmallIntegerField(blank=True, verbose_name='Начало диапазона недель учебного графика ячейки')),
                ('end_week_number', models.PositiveSmallIntegerField(blank=True, verbose_name='Конец диапазона недель учебного графика ячейки')),
                ('edu_form', models.CharField(blank=True, max_length=150, verbose_name='Форма обучения для которой сотавлен график')),
                ('cell', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='complexes.Cell', verbose_name='Ячейка комплекса')),
            ],
            options={
                'verbose_name': 'Неделя календарного учебного графика',
                'verbose_name_plural': 'Недели календарного учебного графика',
            },
        ),
    ]
