# Generated by Django 3.1.4 on 2021-03-10 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complexes', '0001_initial'),
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrystatusprogsubject',
            name='edu_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.eduprogram', verbose_name='Образовательная программа'),
        ),
        migrations.AddField(
            model_name='registrystatusprogsubject',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='complexes.registrystatus', verbose_name='Статус экспертизы комплекса'),
        ),
        migrations.AddField(
            model_name='registrystatusprogsubject',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.subject', verbose_name='Дисциплина'),
        ),
        migrations.AddField(
            model_name='registrystatus',
            name='digital_complex',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='complexes.digitalcomplex', verbose_name='Комплекс ЭМУК'),
        ),
        migrations.AddField(
            model_name='digitalcomplex',
            name='competences',
            field=models.ManyToManyField(blank=True, to='repository.Competence', verbose_name='Компетенции'),
        ),
        migrations.AddField(
            model_name='digitalcomplex',
            name='digital_resources',
            field=models.ManyToManyField(to='repository.DigitalResource', verbose_name='Компоненты ЭУМК'),
        ),
        migrations.AddField(
            model_name='digitalcomplex',
            name='directions',
            field=models.ManyToManyField(blank=True, to='repository.Direction', verbose_name='Направления подготовки'),
        ),
        migrations.AddField(
            model_name='digitalcomplex',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='repository.language', verbose_name='Язык комплекса'),
        ),
    ]
