# Generated by Django 3.1.4 on 2021-02-04 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('repository', '0001_initial'),
        ('complexes', '0002_auto_20210204_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentacademicgroup',
            name='academic_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.academicgroup', verbose_name='Академическая группа'),
        ),
        migrations.AlterField(
            model_name='assignmentacademicgroup',
            name='digital_complex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complexes.digitalcomplex', verbose_name='ЭУМКи'),
        ),
        migrations.AlterField(
            model_name='assignmentacademicgroup',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='repository.subject', verbose_name='Дисциплина'),
        ),
    ]
