# Generated by Django 3.1.4 on 2021-02-19 12:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '__first__'),
        ('repository', '0001_initial'),
        ('complexes', '0002_auto_20210126_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentAcademicGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('learn_date', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Учебный год')),
                ('semestr', models.CharField(blank=True, choices=[('FIRST', 'Первый семестр'), ('SECOND', 'Второй семестр')], max_length=50, null=True, verbose_name='Семестр')),
                ('academic_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.academicgroup', verbose_name='Академическая группа')),
            ],
            options={
                'verbose_name': 'Ресурсное обеспечение академической группы',
                'verbose_name_plural': 'Ресурсное обеспечение академических групп',
            },
        ),
        migrations.AlterModelOptions(
            name='componentcomplex',
            options={'verbose_name': 'компонент комплекса', 'verbose_name_plural': 'компоненты комплексов'},
        ),
        migrations.AlterModelOptions(
            name='platformcomponent',
            options={'verbose_name': 'Компонент платформы', 'verbose_name_plural': 'Компоненты платформ'},
        ),
        migrations.AlterModelOptions(
            name='resourcecomponent',
            options={'verbose_name': 'Компонент ЭОР', 'verbose_name_plural': 'Компоненты ЭОР'},
        ),
        migrations.AlterModelOptions(
            name='traditionalsessioncomponent',
            options={'verbose_name': 'компонент традиционных занятий', 'verbose_name_plural': 'компоненты традиционных занятий'},
        ),
        migrations.AddField(
            model_name='digitalcomplex',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Наименогвание комплекса'),
        ),
        migrations.AlterField(
            model_name='componentcomplex',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание / Методика применения'),
        ),
        migrations.AddField(
            model_name='assignmentacademicgroup',
            name='digital_complex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complexes.digitalcomplex', verbose_name='ЭУМКи'),
        ),
        migrations.AddField(
            model_name='assignmentacademicgroup',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='repository.subject', verbose_name='Дисциплина'),
        ),
    ]
