# Generated by Django 4.1.7 on 2023-03-15 18:42

import auto_prefetch
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("repository", "0002_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("complexes", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitalcomplex",
            name="owner",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owner_digital_complex",
                to="users.person",
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="digitalcomplex",
            name="results_edu",
            field=models.ManyToManyField(
                blank=True,
                to="repository.resultedu",
                verbose_name="Результаты обучения",
            ),
        ),
        migrations.AddField(
            model_name="digitalcomplex",
            name="subjects",
            field=models.ManyToManyField(
                blank=True,
                related_name="subjects",
                to="repository.subject",
                verbose_name="Дисциплина(ы)",
            ),
        ),
        migrations.AddField(
            model_name="complexparentcomponent",
            name="digital_complex",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="complexes.digitalcomplex",
                verbose_name="ЭУМК",
            ),
        ),
        migrations.AddField(
            model_name="complexparentcomponent",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="assignmentacademicgroup",
            name="academic_group",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.academicgroup",
                verbose_name="Академическая группа",
            ),
        ),
        migrations.AddField(
            model_name="assignmentacademicgroup",
            name="digital_complex",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="complexes.digitalcomplex",
                verbose_name="ЭУМКи",
            ),
        ),
        migrations.AddField(
            model_name="assignmentacademicgroup",
            name="group_subject",
            field=smart_selects.db_fields.ChainedForeignKey(
                blank=True,
                chained_field="academic_group",
                chained_model_field="academic_group",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.groupdisciplines",
                verbose_name="Дисциплина/Семестр",
            ),
        ),
        migrations.AddField(
            model_name="resourcecomponent",
            name="digital_resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="repository.digitalresource",
                verbose_name="ЭОР",
            ),
        ),
    ]
