# Generated by Django 3.1.4 on 2021-02-05 08:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
        ('complexes', '0003_auto_20210204_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentacademicgroup',
            name='semestr',
            field=models.CharField(blank=True, choices=[('FIRST', 'Первый семестр'), ('SECOND', 'Второй семестр')], max_length=50, null=True, verbose_name='Семестр'),
        ),
        migrations.CreateModel(
            name='EduProvidingDiscipline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('assignment_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='complexes.assignmentacademicgroup', verbose_name='Ресурсное обеспечение академической группы')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='repository.direction', verbose_name='Образовательная программа/Направление подготовки')),
            ],
            options={
                'verbose_name': 'Учебно-методическое обеспечение дисциплины',
                'verbose_name_plural': 'Учебно-методическое обеспечение дисциплин',
            },
        ),
    ]
