# Generated by Django 4.2.3 on 2023-07-13 01:38

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("complexes", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignmentacademicgroup",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "ресурсное обеспечение академической группы",
                "verbose_name_plural": "ресурсное обеспечение академических групп",
            },
        ),
        migrations.AlterModelOptions(
            name="complexparentcomponent",
            options={
                "base_manager_name": "prefetch_manager",
                "ordering": ["order"],
                "verbose_name": "компонент комплекса",
                "verbose_name_plural": "компоненты комплексов",
            },
        ),
        migrations.AlterModelOptions(
            name="digitalcomplex",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "цифровой Комплекс (ЭУМК)",
                "verbose_name_plural": "цифровые Комплексы (ЭУМК)",
            },
        ),
        migrations.AlterModelOptions(
            name="literarysourcescomponent",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "литературный источник",
                "verbose_name_plural": "литературные источники",
            },
        ),
        migrations.AlterModelOptions(
            name="plancomponent",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "компонент",
                "verbose_name_plural": "компоненты структурно-тематического плана",
            },
        ),
        migrations.AlterModelOptions(
            name="platformcomponent",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "среда обучения",
                "verbose_name_plural": "среда обучения",
            },
        ),
        migrations.AlterModelOptions(
            name="resourcecomponent",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "компонент ЭОР",
                "verbose_name_plural": "компоненты ЭОР",
            },
        ),
        migrations.AlterModelOptions(
            name="thematicplan",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "структурно-тематический план",
                "verbose_name_plural": "структурно-тематические планы",
            },
        ),
        migrations.AlterModelOptions(
            name="theme",
            options={
                "base_manager_name": "prefetch_manager",
                "ordering": ["order"],
                "verbose_name": "тема",
                "verbose_name_plural": "темы структурно-тематического плана",
            },
        ),
        migrations.AlterModelOptions(
            name="traditionalsessioncomponent",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "синхронное занятие",
                "verbose_name_plural": "синхронные занятия",
            },
        ),
        migrations.AlterModelManagers(
            name="plancomponent",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="theme",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
