# Generated by Django 3.1.4 on 2021-03-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0004_auto_20210316_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='literarysourcescomponent',
            options={'verbose_name': 'Литературный источник', 'verbose_name_plural': 'Литературные источники'},
        ),
        migrations.AddField(
            model_name='literarysourcescomponent',
            name='title',
            field=models.CharField(blank=True, max_length=424, null=True, verbose_name='Библиографическая ссылка'),
        ),
        migrations.AddField(
            model_name='literarysourcescomponent',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL-ссылка'),
        ),
    ]
