# Generated by Django 3.1.4 on 2021-02-05 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0004_auto_20210205_1352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EduProvidingDiscipline',
        ),
    ]
