# Generated by Django 3.1.4 on 2021-02-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0005_delete_eduprovidingdiscipline'),
        ('complexes', '0003_auto_20210219_1747'),
    ]

    operations = [
    ]
