# Generated by Django 3.1.4 on 2021-04-21 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0006_auto_20210421_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complexspacecell',
            name='cells',
        ),
        migrations.AddField(
            model_name='cell',
            name='digital_complex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complexes.digitalcomplex', verbose_name='Комплекс ЭУМК'),
        ),
        migrations.AddField(
            model_name='cell',
            name='theme_name',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Тема / Раздел'),
        ),
        migrations.AlterField(
            model_name='complexspacecell',
            name='digital_complex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complexes.digitalcomplex', verbose_name='Комплекс ЭУМК'),
        ),
    ]
