# Generated by Django 3.1.4 on 2021-04-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('complexes', '0008_auto_20210427_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalcomplex',
            name='format',
            field=models.CharField(blank=True, choices=[('0', 'смешанное обучение (Ауд+Дист+ЭИОС)'),
                                                        ('1', 'смешанное обучение (Ауд+Дист)'),
                                                        ('2', 'смешанное обучение (Ауд+ЭИОС)'),
                                                        ('3', 'дистанционное обучение (Дист+ЭИОС)'),
                                                        ('4', 'дистанционное обучение (Дист)'),
                                                        ('5', 'исключительно электронное обучение'),
                                                        ('6', 'традиционное обучение')], max_length=300,
                                   verbose_name='Формат использования'),
        ),
    ]
