# Generated by Django 3.1.4 on 2021-04-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0009_auto_20210428_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalcomplex',
            name='title',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Наименование комплекса'),
        ),
    ]
