# Generated by Django 3.1.4 on 2021-04-29 14:21

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0010_auto_20210429_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complextheme',
            name='digital_complex',
        ),
        migrations.RemoveField(
            model_name='registrystatus',
            name='digital_complex',
        ),
        migrations.RemoveField(
            model_name='registrystatusprogsubject',
            name='edu_program',
        ),
        migrations.RemoveField(
            model_name='registrystatusprogsubject',
            name='status',
        ),
        migrations.RemoveField(
            model_name='registrystatusprogsubject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='beg_theme_number',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='digital_complex',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='end_theme_number',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='theme_name',
        ),
        migrations.RemoveField(
            model_name='complexspacecell',
            name='description',
        ),
        migrations.RemoveField(
            model_name='complexspacecell',
            name='link',
        ),
        migrations.RemoveField(
            model_name='complexspacecell',
            name='title',
        ),
        migrations.RemoveField(
            model_name='digitalcomplex',
            name='digital_resources',
        ),
        migrations.AddField(
            model_name='cell',
            name='component_complexes',
            field=models.ManyToManyField(blank=True, to='complexes.ComponentComplex', verbose_name='Компоненты ЭУМК'),
        ),
        migrations.AddField(
            model_name='cell',
            name='week_range',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True, verbose_name='Диапозон '),
        ),
        migrations.AddField(
            model_name='complexspacecell',
            name='cell_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Координаты ячеек'),
        ),
        migrations.AddField(
            model_name='complexspacecell',
            name='theme_name',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Тема / Раздел'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='methodology_description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Методологическое описание'),
        ),
        migrations.AlterField(
            model_name='componentcomplex',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядрок отображения компонента'),
        ),
        migrations.DeleteModel(
            name='CellWeeks',
        ),
        migrations.DeleteModel(
            name='ComplexTheme',
        ),
        migrations.DeleteModel(
            name='RegistryStatus',
        ),
        migrations.DeleteModel(
            name='RegistryStatusProgSubject',
        ),
    ]
