# Generated by Django 3.1.4 on 2021-04-30 03:22

import uuid

import django.db.models.deletion
import sortedm2m.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('complexes', '0011_auto_20210429_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('type', models.CharField(choices=[('theory', 'Теория'), ('practice', 'Практика')], default='theory',
                                          max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', sortedm2m.fields.SortedManyToManyField(help_text=None, to='complexes.Container')),
            ],
        ),
        migrations.AlterModelOptions(
            name='cell',
            options={},
        ),
        migrations.RemoveField(
            model_name='cell',
            name='component_complexes',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='include_practice',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='include_theory',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='methodology_description',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='type',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='week_range',
        ),
        migrations.AddField(
            model_name='cell',
            name='content',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='complexes.ComponentComplex'),
        ),
        migrations.DeleteModel(
            name='ComplexSpaceCell',
        ),
        migrations.AddField(
            model_name='cell',
            name='end_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                    to='complexes.container'),
        ),
        migrations.AddField(
            model_name='cell',
            name='start_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                    to='complexes.container'),
        ),
        migrations.AddField(
            model_name='digitalcomplex',
            name='thematic_plan',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='complexes.Theme'),
        ),
    ]
