# Generated by Django 3.1.10 on 2021-05-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0012_auto_20210430_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='content',
            field=models.ManyToManyField(to='complexes.Container'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='title',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
