# Generated by Django 3.1.10 on 2021-05-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0014_bookmarkdigitalresource'),
        ('complexes', '0012_auto_20210430_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalcomplex',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='repository.Subject', verbose_name='Дисциплина(ы)'),
        ),
    ]
