# Generated by Django 3.1.10 on 2021-05-14 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0013_auto_20210514_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='digitalcomplex',
            name='thematic_plan',
        ),
        migrations.AddField(
            model_name='theme',
            name='complex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thematic_plan', to='complexes.digitalcomplex'),
        ),
        migrations.AddField(
            model_name='theme',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='digitalcomplex',
            name='title',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150, null=True, verbose_name='Наименование комплекса'),
        ),
    ]
