# Generated by Django 3.1.10 on 2021-06-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0013_auto_20210517_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalcomplex',
            name='form_control',
            field=models.CharField(blank=True, choices=[('0', 'зачет'), ('1', 'экзамен ')], max_length=300, null=True, verbose_name='Форма контроля'),
        ),
    ]
