# Generated by Django 3.1.10 on 2021-06-21 03:56

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210518_1338'),
        ('complexes', '0014_digitalcomplex_form_control'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentacademicgroup',
            name='semestr',
        ),
        migrations.RemoveField(
            model_name='assignmentacademicgroup',
            name='subject',
        ),
        migrations.AddField(
            model_name='assignmentacademicgroup',
            name='group_subject',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='academic_group', chained_model_field='academic_group', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.groupdisciplines', verbose_name='Дисциплина группы '),
        ),
        migrations.AlterField(
            model_name='componentcomplex',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Как используется при изучении дисциплины'),
        ),
        migrations.AlterField(
            model_name='platformcomponent',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
