# Generated by Django 3.1.10 on 2021-06-21 06:04

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210621_1020'),
        ('complexes', '0018_auto_20210621_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentacademicgroup',
            old_name='academic_group',
            new_name='academic_group_test',
        ),
        migrations.AlterField(
            model_name='assignmentacademicgroup',
            name='group_subject',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='academic_group_test', chained_model_field='academic_group', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.groupdisciplines', verbose_name='Дисциплина группы'),
        ),
    ]
