# Generated by Django 3.1.10 on 2021-06-21 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0019_auto_20210621_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentacademicgroup',
            name='academic_group_test',
        ),
    ]
