# Generated by Django 3.1.10 on 2021-06-21 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210621_1020'),
        ('complexes', '0020_remove_assignmentacademicgroup_academic_group_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentacademicgroup',
            name='academic_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.academicgroup', verbose_name='Академическая группа'),
        ),
    ]
