# Generated by Django 3.1.10 on 2021-06-23 11:01

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_student_academic_group'),
        ('complexes', '0021_assignmentacademicgroup_academic_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentacademicgroup',
            name='group_subject',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='academic_group', chained_model_field='academic_group', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.groupdisciplines', verbose_name='Дисциплина/Семестр'),
        ),
        migrations.AlterField(
            model_name='literarysourcescomponent',
            name='title',
            field=models.TextField(blank=True, max_length=424, null=True, verbose_name='Библиографическая ссылка'),
        ),
    ]
