# Generated by Django 3.1.12 on 2021-07-26 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0022_auto_20210623_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['order']},
        ),
        # migrations.RemoveField(
        #     model_name='digitalcomplex',
        #     name='thematic_plan',
        # ),
        # migrations.AddField(
        #     model_name='theme',
        #     name='complex',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thematic_plan', to='complexes.digitalcomplex'),
        # ),
        # migrations.AddField(
        #     model_name='theme',
        #     name='order',
        #     field=models.PositiveSmallIntegerField(default=0),
        # ),
        migrations.AlterField(
            model_name='literarysourcescomponent',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Библиографическая ссылка'),
        ),
        migrations.AlterField(
            model_name='platformcomponent',
            name='description_self',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='platformcomponent',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на онлайн-расписание занятий'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='content',
            field=models.ManyToManyField(to='complexes.Container'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='title',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
