# Generated by Django 3.1.12 on 2021-06-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0022_auto_20210623_1601'),
        ('complexes', '0014_auto_20210514_1721'),
    ]

    operations = [
    ]
