# Generated by Django 3.1.12 on 2021-06-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0023_merge_20210627_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalcomplex',
            name='title',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Наименование комплекса'),
        ),
        migrations.AlterField(
            model_name='literarysourcescomponent',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Библиографическая ссылка'),
        ),
        migrations.AlterField(
            model_name='platformcomponent',
            name='description_self',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='platformcomponent',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на онлайн-расписание занятий'),
        ),
    ]
