# Generated by Django 3.1.12 on 2021-08-22 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0024_auto_20210628_1030'),
        ('complexes', '0023_auto_20210726_1435'),
    ]

    operations = [
    ]
