# Generated by Django 3.2.6 on 2021-09-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0027_digitalcomplex_form_control'),
    ]

    operations = [

    ]
