# Generated by Django 3.2.6 on 2021-09-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0028_digitalcomplex_form_control'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='digitalcomplex',
        #     name='form_control',
        #     field=models.CharField(blank=True, choices=[('0', 'зачет'), ('1', 'экзамен ')], max_length=300, null=True, verbose_name='Форма контроля'),
        # ),
    ]
