# Generated by Django 3.2.6 on 2021-09-15 11:58

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0027_digitalcomplex_form_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThematicPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('plan_object', models.JSONField(blank=True, null=True, verbose_name='Объект плана')),
                ('digital_complex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complexes.digitalcomplex', verbose_name='Цифровой Комплекс (ЭУМК)')),
            ],
            options={
                'verbose_name': 'Структурно-тематический план',
                'verbose_name_plural': 'Структурно-тематические планы',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
