# Generated by Django 3.2.8 on 2021-10-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0030_auto_20211018_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalcomplex',
            name='form_control',
            field=models.CharField(choices=[('-', 'Не определено'), ('0', 'зачет'), ('1', 'экзамен ')], default='-', max_length=1, verbose_name='Форма контроля'),
        ),
        migrations.AlterField(
            model_name='digitalcomplex',
            name='format',
            field=models.CharField(choices=[('-', 'Не определено'), ('0', 'смешанное обучение (Ауд+Дист+ЭИОС)'), ('1', 'смешанное обучение (Ауд+Дист)'), ('2', 'смешанное обучение (Ауд+ЭИОС)'), ('3', 'дистанционное обучение (Дист+ЭИОС)'), ('4', 'дистанционное обучение (Дист)'), ('5', 'исключительно электронное обучение'), ('6', 'традиционное обучение')], default='-', max_length=1, verbose_name='Формат использования'),
        ),
    ]
