# Generated by Django 3.2.8 on 2021-10-18 15:26

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('complexes', '0032_auto_20211018_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalcomplex',
            name='keywords',
        ),
        migrations.AddField(
            model_name='digitalcomplex',
            name='keywords',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Ключевые слова'),
        ),
    ]
