# Generated by Django 3.2.8 on 2021-10-18 17:39

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0034_auto_20211018_2037_squashed_0036_auto_20211018_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name': 'компонент', 'verbose_name_plural': 'компоненты структурно-тематического плана'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['order'], 'verbose_name': 'тема', 'verbose_name_plural': 'темы структурно-тематического плана'},
        ),
        migrations.AddField(
            model_name='component',
            name='methodology_description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Методологическое описание'),
        ),
        migrations.AddField(
            model_name='component',
            name='type',
            field=models.CharField(choices=[('UNKNOWN', 'не определено'), ('ASYNC', 'асинхронные мероприятия'), ('SYNC', 'синхронные мероприятия')], max_length=7, null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='component',
            name='week_range',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True, verbose_name='Диапазон'),
        ),
    ]
