# Generated by Django 3.2.8 on 2021-10-18 18:28

import auto_prefetch
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0035_auto_20211018_2239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Component',
            new_name='PlanComponent',
        ),
        migrations.AlterModelOptions(
            name='assignmentacademicgroup',
            options={'verbose_name': 'ресурсное обеспечение академической группы', 'verbose_name_plural': 'ресурсное обеспечение академических групп'},
        ),
        migrations.AlterModelOptions(
            name='digitalcomplex',
            options={'verbose_name': 'цифровой Комплекс (ЭУМК)', 'verbose_name_plural': 'цифровые Комплексы (ЭУМК)'},
        ),
        migrations.AlterModelOptions(
            name='literarysourcescomponent',
            options={'verbose_name': 'литературный источник', 'verbose_name_plural': 'литературные источники'},
        ),
        migrations.AlterModelOptions(
            name='platformcomponent',
            options={'verbose_name': 'среда обучения', 'verbose_name_plural': 'среда обучения'},
        ),
        migrations.AlterModelOptions(
            name='resourcecomponent',
            options={'verbose_name': 'компонент ЭОР', 'verbose_name_plural': 'компоненты ЭОР'},
        ),
        migrations.AlterModelOptions(
            name='traditionalsessioncomponent',
            options={'verbose_name': 'синхронное занятие', 'verbose_name_plural': 'синхронные занятия'},
        ),
        migrations.AlterField(
            model_name='componentcomplex',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Как используется при изучении дисциплины'),
        ),
        migrations.AlterField(
            model_name='digitalcomplex',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='platformcomponent',
            name='description_self',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='thematicplan',
            name='digital_complex',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thematic_plan', to='complexes.digitalcomplex', verbose_name='Цифровой Комплекс (ЭУМК)'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='thematic_plan',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='complexes.thematicplan'),
        ),
        migrations.AlterField(
            model_name='traditionalsessioncomponent',
            name='description_session',
            field=models.TextField(blank=True, null=True, verbose_name='Описание занятий'),
        ),
    ]
