# Generated by Django 3.2.8 on 2021-10-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0036_auto_20211018_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancomponent',
            name='methodology_description',
            field=models.TextField(blank=True, null=True, verbose_name='Методологическое описание'),
        ),
    ]
