# Generated by Django 3.2.8 on 2021-10-18 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0037_alter_plancomponent_methodology_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thematicplan',
            options={'verbose_name': 'структурно-тематический план', 'verbose_name_plural': 'структурно-тематические планы'},
        ),
    ]
