# Generated by Django 3.2.8 on 2021-10-18 21:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('repository', '0023_auto_20211018_2339'),
        ('complexes', '0038_alter_thematicplan_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiterarySourcesComponent'
        ),
        migrations.DeleteModel(
            name='PlatformComponent'
        ),
        migrations.DeleteModel(
            name='ResourceComponent'
        ),
        migrations.DeleteModel(
            name='TraditionalSessionComponent'
        ),
        migrations.DeleteModel(
            name='ComponentComplex'
        ),

    ]
