# Generated by Django 3.2.8 on 2021-10-18 22:15

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('repository', '0023_auto_20211018_2339'),
        ('complexes', '0039_auto_20211019_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplexParentComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Как используется при изучении дисциплины')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Порядрок отображения компонента')),
                ('digital_complex', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='complexes.digitalcomplex', verbose_name='ЭУМК')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_complexes.complexparentcomponent_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'компонент комплекса',
                'verbose_name_plural': 'компоненты комплексов',
                'ordering': ['order'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LiterarySourcesComponent',
            fields=[
                ('complexparentcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='complexes.complexparentcomponent')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Библиографическая ссылка')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'литературный источник',
                'verbose_name_plural': 'литературные источники',
            },
            bases=('complexes.complexparentcomponent',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PlatformComponent',
            fields=[
                ('complexparentcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='complexes.complexparentcomponent')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Наименование')),
                ('description_self', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на онлайн-расписание занятий')),
            ],
            options={
                'verbose_name': 'среда обучения',
                'verbose_name_plural': 'среда обучения',
            },
            bases=('complexes.complexparentcomponent',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TraditionalSessionComponent',
            fields=[
                ('complexparentcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='complexes.complexparentcomponent')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Наименование вида занятий')),
                ('description_session', models.TextField(blank=True, null=True, verbose_name='Описание занятий')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на онлайн-расписание занятий')),
            ],
            options={
                'verbose_name': 'синхронное занятие',
                'verbose_name_plural': 'синхронные занятия',
            },
            bases=('complexes.complexparentcomponent',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ResourceComponent',
            fields=[
                ('complexparentcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='complexes.complexparentcomponent')),
                ('digital_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.digitalresource', verbose_name='ЭОР')),
            ],
            options={
                'verbose_name': 'компонент ЭОР',
                'verbose_name_plural': 'компоненты ЭОР',
            },
            bases=('complexes.complexparentcomponent',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
