# Generated by Django 4.1.7 on 2023-03-15 18:42

import auto_prefetch
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import polymorphic.showfields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookmarkDigitalResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последние обновление"
                    ),
                ),
            ],
            options={
                "db_table": "bookmark__digital_resource",
            },
        ),
        migrations.CreateModel(
            name="Competence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последние обновление"
                    ),
                ),
                ("title", models.TextField(verbose_name="Наименование")),
                ("code", models.CharField(max_length=8, verbose_name="Код")),
                ("okso", models.CharField(max_length=8, null=True, verbose_name="Код")),
            ],
            options={
                "verbose_name": "компетенция",
                "verbose_name_plural": "компетенции",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CompetenceGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=400, verbose_name="Наименование")),
            ],
        ),
        migrations.CreateModel(
            name="DigitalResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последние обновление"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=1024, verbose_name="Наименование ресурса"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("OK", "Онлайн-курс"),
                            ("EUK", "ЭУК"),
                            (
                                "TEXT_EOR",
                                "Текстовый электронный образовательный ресурс",
                            ),
                            (
                                "MULTIMEDIA_EOR",
                                "Мультимедийный электронный образовательный ресурс",
                            ),
                        ],
                        max_length=30,
                        null=True,
                        verbose_name="Тип ресурса",
                    ),
                ),
                (
                    "source_data",
                    models.CharField(
                        choices=[("MANUAL", "вручную"), ("IMPORT", "импорт")],
                        default="MANUAL",
                        max_length=30,
                        verbose_name="Источник данных",
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        max_length=6024,
                        null=True,
                        verbose_name="Ключевые слова",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "паспорт ЭОР",
                "verbose_name_plural": "паспорта ЭОР",
                "ordering": ["title"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Direction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последние обновление"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Наименование"
                    ),
                ),
                (
                    "uni_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=8, verbose_name="Код направления"
                    ),
                ),
            ],
            options={
                "verbose_name": "направление подготовки",
                "verbose_name_plural": "направления подготовки",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="DirectionsEnlargedGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последние обновление"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=128, verbose_name="Наименование УГН"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Код УГН"
                    ),
                ),
            ],
            options={
                "verbose_name": "укрупненная группа направлений",
                "verbose_name_plural": "укрупненные группа направлений",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="EduProgram",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последние обновление"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=450, verbose_name="Наименование"
                    ),
                ),
                (
                    "_cipher",
                    models.CharField(
                        blank=True, max_length=5, null=True, verbose_name="Шифр ОП"
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Короткое описание",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "standard",
                    models.CharField(
                        blank=True, max_length=9, null=True, verbose_name="Стандарт"
                    ),
                ),
                (
                    "edu_level",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="Уровень подготовки",
                    ),
                ),
                (
                    "admission_years",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            blank=True, null=True
                        ),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "approve_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Год утверждения"
                    ),
                ),
                (
                    "head",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Руководитель",
                    ),
                ),
                (
                    "site_admin",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Администратор сайта ОП",
                    ),
                ),
                (
                    "direction",
                    auto_prefetch.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="repository.direction",
                        verbose_name="Направление подготовки",
                    ),
                ),
            ],
            options={
                "verbose_name": "образовательная программа",
                "verbose_name_plural": "образовательные программы",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="EduProgramSubject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "дисциплина/образовательная программа",
                "verbose_name_plural": "дисциплины/образовательные программы",
            },
            bases=(polymorphic.showfields.ShowFieldType, models.Model),
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                ("title", models.CharField(max_length=80, verbose_name="Наименование")),
                (
                    "code",
                    models.CharField(
                        max_length=4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Код языка",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последние обновление"
                    ),
                ),
            ],
            options={
                "verbose_name": "язык ресура",
                "verbose_name_plural": "языки ресурсов",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последние обновление"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="Наименование"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "url_logo",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на логотип"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="upload/images/",
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "contacts",
                    models.TextField(blank=True, null=True, verbose_name="Контакты"),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL")),
            ],
            options={
                "verbose_name": "организация",
                "verbose_name_plural": "организации",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последние обновление"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Наименование"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                ("url", models.URLField(verbose_name="Ссылка")),
                (
                    "url_logo",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на логотип"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="upload/images/",
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "contacts",
                    models.TextField(blank=True, null=True, verbose_name="Контакты"),
                ),
            ],
            options={
                "verbose_name": "платформа",
                "verbose_name_plural": "платформы",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ScientificBranch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последние обновление"
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="Наименование")),
                (
                    "code",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Код"
                    ),
                ),
            ],
            options={
                "verbose_name": "научная отрасль",
                "verbose_name_plural": "научные отрасли",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последние обновление"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Наименование"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "labor",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Трудоемкость"
                    ),
                ),
            ],
            options={
                "verbose_name": "дисциплина",
                "verbose_name_plural": "дисциплины",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="EduProgramChild",
            fields=[
                (
                    "eduprogramsubject_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="repository.eduprogramsubject",
                    ),
                ),
            ],
            options={
                "verbose_name": "образовательная программа",
                "verbose_name_plural": "образовательные программы",
            },
            bases=("repository.eduprogramsubject",),
        ),
        migrations.CreateModel(
            name="SubjectChild",
            fields=[
                (
                    "eduprogramsubject_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="repository.eduprogramsubject",
                    ),
                ),
            ],
            options={
                "verbose_name": "дисциплина",
                "verbose_name_plural": "дисциплины",
            },
            bases=("repository.eduprogramsubject",),
        ),
        migrations.CreateModel(
            name="SubjectTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последние обновление"
                    ),
                ),
                (
                    "tag",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="repository.subject",
                        verbose_name="Дисциплина",
                    ),
                ),
            ],
            options={
                "verbose_name": "тег дисциплины",
                "verbose_name_plural": "теги дисциплин",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последние обновление"
                    ),
                ),
                (
                    "link_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Наименование",
                    ),
                ),
                ("URL", models.URLField(blank=True, null=True, verbose_name="Ссылка")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="upload/files",
                        verbose_name="Файл",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("URL", "URL"), ("FILE", "Файл")],
                        max_length=8,
                        null=True,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "digital_resource",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="repository.digitalresource",
                        verbose_name="Паспорт ЭОР",
                    ),
                ),
            ],
            options={
                "verbose_name": "компонент",
                "verbose_name_plural": "компоненты",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ResultEdu",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последние обновление"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="Наименование"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "competence",
                    auto_prefetch.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="repository.competence",
                        verbose_name="Компетенция",
                    ),
                ),
            ],
            options={
                "verbose_name": "образовательный результат",
                "verbose_name_plural": "образовательные результаты",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="EduProgramTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последние обновление"
                    ),
                ),
                (
                    "tag",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="repository.eduprogram",
                        verbose_name="Образовательная программа",
                    ),
                ),
            ],
            options={
                "verbose_name": "тег образовательной программы",
                "verbose_name_plural": "теги образовательных программ",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="direction",
            name="scientific_branch",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="directions",
                to="repository.scientificbranch",
                verbose_name="Научная отрасль",
            ),
        ),
    ]
