# Generated by Django 3.0.7 on 2020-07-13 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lrr.repository.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(max_length=1024, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('image', models.ImageField(upload_to='images/author/photos/', verbose_name='Фото')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, verbose_name='Код компетенции')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='CompetenceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.CharField(max_length=1024, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('labor', models.PositiveSmallIntegerField(verbose_name='Трудоемкость')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='DisciplineTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.CharField(max_length=255, verbose_name='Индекс')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=4, verbose_name='Код языка')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', models.TextField(max_length=1024, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('logo', models.ImageField(upload_to='images/org/logo/', verbose_name='Логотип')),
                ('site_url', models.URLField(max_length=255, verbose_name='URL сайта')),
                ('contacts', models.TextField(max_length=1024, verbose_name='Контакты')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('logo', models.ImageField(upload_to='images/platforms/logo/', verbose_name='Логотип')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
                ('description', models.TextField(max_length=1024, verbose_name='Описание')),
                ('contacts', models.TextField(max_length=1024, verbose_name='Контакты')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ResourceStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=150, verbose_name='Статус')),
                ('model', models.CharField(max_length=255, verbose_name='Модель использования')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('due_date', models.CharField(max_length=255, verbose_name='Статус')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link', models.URLField(max_length=255, verbose_name='Ссылка')),
                ('status', models.CharField(max_length=255, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('type', models.CharField(max_length=255, verbose_name='Тип')),
                ('file', models.FileField(upload_to=lrr.repository.models.get_source_path, verbose_name='Файл')),
                ('priority', models.PositiveIntegerField(verbose_name='Приоритет')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ThematicPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thematicplans', to='repository.Discipline')),
                ('themes', models.ManyToManyField(related_name='thematicplans', to='repository.ThematicPlan')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='DisciplineThemeResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('digital_resource_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinethemeresources', to='repository.Source')),
                ('discipline_themes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinethemeresources', to='repository.DisciplineTheme')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='DigitalResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=1024, verbose_name='Наименование')),
                ('type', models.TextField(max_length=100, verbose_name='Тип')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('keywords', models.CharField(max_length=150, verbose_name='Ключевые слова')),
                ('format', models.CharField(max_length=30)),
                ('content_count', models.PositiveIntegerField(verbose_name='Показатель объема контента')),
                ('usage_stats', models.PositiveIntegerField(verbose_name='Показатель использования')),
                ('programs_count', models.PositiveIntegerField(verbose_name='Показатель назначения')),
                ('authors', models.ManyToManyField(related_name='digitalresources', to='repository.Author')),
                ('competences', models.ManyToManyField(related_name='digitalresources', to='repository.Competence')),
                ('directions', models.ManyToManyField(related_name='digitalresources', to='repository.Direction')),
                ('disciplines', models.ManyToManyField(related_name='digitalresources', to='repository.Discipline')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digitalresources', to='repository.Language')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digitalresources', to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digitalresources', to='repository.Platform')),
                ('rightholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digitalresources', to='repository.Organisation')),
                ('sources', models.ManyToManyField(related_name='digitalresources', to='repository.Source')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digitalresources', to='repository.ResourceStatus')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='competence',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competences', to='repository.CompetenceCategory'),
        ),
    ]
