# Generated by Django 3.0.7 on 2020-10-01 12:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('code', models.CharField(max_length=8, verbose_name='Код компетенции')),
            ],
            options={
                'verbose_name': 'Компетенция',
                'verbose_name_plural': 'Компетенции',
            },
        ),
        migrations.CreateModel(
            name='ConformityTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('practice', models.NullBooleanField(verbose_name='Практика')),
                ('theory', models.NullBooleanField(verbose_name='Теория')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
            ],
            options={
                'verbose_name': 'Соответствие ЦОР темам дисциплины',
                'verbose_name_plural': 'Соответствия ЦОР темам дисциплин',
            },
        ),
        migrations.CreateModel(
            name='DigitalResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('title', models.CharField(max_length=1024, verbose_name='Наименование ресурса')),
                ('type', models.CharField(choices=[('OK', 'Онлайн-курс'), ('EUK', 'ЭУК'), ('TEXT_EOR', 'Текстовый электронный образовательный ресурс'), ('MULTIMEDIA_EOR', 'Мультимедийный электронный образовательный ресурс')], max_length=30, null=True, verbose_name='Тип ресурса')),
                ('source_data', models.CharField(choices=[('MANUAL', 'вручную'), ('IMPORT', 'импорт')], default='MANUAL', max_length=30, verbose_name='Источник данных')),
                ('keywords', models.CharField(blank=True, max_length=6024, null=True, verbose_name='Ключевые слова')),
                ('description', models.TextField(blank=True, max_length=6024, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Паспорт ЦОР',
                'verbose_name_plural': 'Паспорта ЦОР',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='DRStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('quality_category', models.CharField(blank=True, choices=[('INNER', 'внутренний'), ('OUTER', 'внешний'), ('OUTSIDE', 'сторонний')], max_length=30, verbose_name='Категория качества')),
                ('interactive_category', models.CharField(blank=True, choices=[('NOT_INTERACTIVE', 'не интерактивный'), ('WITH_TEACHER_SUPPORT', 'с поддержкой преподавателя'), ('AUTO', 'автоматизированный')], max_length=30, verbose_name='Категория интерактивности')),
            ],
            options={
                'verbose_name': 'Статус ЦОР',
                'verbose_name_plural': 'Статусы ЦОР',
            },
        ),
        migrations.CreateModel(
            name='EduProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('title', models.CharField(max_length=450, verbose_name='Наименование')),
                ('short_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Короткое описание')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Образовательная программа',
                'verbose_name_plural': 'Образовательные программы',
            },
        ),
        migrations.CreateModel(
            name='EduProgramTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
            ],
            options={
                'verbose_name': 'Тэг образовательной программы',
                'verbose_name_plural': 'Тэги образовательных программ',
            },
        ),
        migrations.CreateModel(
            name='ExpertiseStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('end_date', models.DateTimeField(verbose_name='Срок действия')),
                ('status', models.CharField(choices=[('NO_INIT', 'не инициирована'), ('SUB_APP', 'подана заявка'), ('ON_EXPERTISE', 'на экспертизе'), ('ON_REVISION', 'на доработку'), ('ASSIGNED_STATUS', 'присвоен статус')], default='NO_INIT', max_length=30, verbose_name='Состояние экспертизы')),
                ('accepted_status', models.BooleanField(default=False, verbose_name='Утверждено (присвоен статус)')),
            ],
            options={
                'verbose_name': 'Статус экспертизы',
                'verbose_name_plural': 'Статусы экспертиз',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('title', models.CharField(max_length=80, verbose_name='Наименование')),
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Код языка')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
            ],
            options={
                'verbose_name': 'Язык ресура',
                'verbose_name_plural': 'Языки ресурсов',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('url_logo', models.URLField(blank=True, null=True, verbose_name='Ссылка на логотип')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='upload/images/', verbose_name='Логотип')),
                ('contacts', models.TextField(blank=True, max_length=500, null=True, verbose_name='Контакты')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('url_logo', models.URLField(blank=True, null=True, verbose_name='Ссылка на логотип')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='upload/images/', verbose_name='Логотип')),
                ('contacts', models.TextField(blank=True, max_length=500, null=True, verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Платформа',
                'verbose_name_plural': 'Платформы',
            },
        ),
        migrations.CreateModel(
            name='ProvidingDiscipline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('rate', models.PositiveIntegerField(verbose_name='Процент покрытия')),
            ],
            options={
                'verbose_name': 'Рекомендация ЦОР в качестве обеспечения дисциплины',
                'verbose_name_plural': 'Рекомендации ЦОР в качестве обеспечения дисциплин',
            },
        ),
        migrations.CreateModel(
            name='ResultEdu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Образовательный результат',
                'verbose_name_plural': 'Образовательные результаты',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('link_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Наименование файла')),
                ('URL', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('file', models.FileField(blank=True, null=True, upload_to='upload/files')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('labor', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Трудоемкость')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='SubjectTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
            ],
            options={
                'verbose_name': 'Тэг дисциплины',
                'verbose_name_plural': 'Тэги дисциплин',
            },
        ),
        migrations.CreateModel(
            name='SubjectTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('title', models.CharField(max_length=150, verbose_name='Наимаенование')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тема дисциплины',
                'verbose_name_plural': 'Темы дисциплин',
            },
        ),
        migrations.CreateModel(
            name='ThematicPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тематический план',
                'verbose_name_plural': 'Тематические планы',
            },
        ),
        migrations.CreateModel(
            name='WorkPlanAcademicGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('semestr', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Семестр')),
            ],
            options={
                'verbose_name': 'Ресурсное обеспечение академической группы',
                'verbose_name_plural': 'Ресурсное обеспечение академических групп',
            },
        ),
    ]
