# Generated by Django 3.1.4 on 2021-03-10 11:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [

        migrations.AddField(
            model_name='digitalresource',
            name='conformity_theme',
            field=models.ManyToManyField(blank=True, to='repository.ConformityTheme', verbose_name='Соответствие ЭОР темам дисциплины'),
        ),
        migrations.AddField(
            model_name='digitalresource',
            name='copyright_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='repository.organization', verbose_name='Правообладатель'),
        ),
        migrations.AddField(
            model_name='digitalresource',
            name='edu_programs_tags',
            field=models.ManyToManyField(blank=True, to='repository.EduProgramTag', verbose_name='Тэги образовательных программ ЭОР'),
        ),
        migrations.AddField(
            model_name='digitalresource',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='repository.language', verbose_name='Язык ресурса'),
        ),
        migrations.AddField(
            model_name='digitalresource',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_digital_resource', to='users.person', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='digitalresource',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='repository.platform', verbose_name='Платформа'),
        ),
        migrations.AddField(
            model_name='digitalresource',
            name='provided_disciplines',
            field=models.ManyToManyField(blank=True, to='repository.ProvidingDiscipline', verbose_name='ЭОР рекомендован в качестве обеспечения дисциплины'),
        ),
        migrations.AddField(
            model_name='digitalresource',
            name='result_edu',
            field=models.ManyToManyField(blank=True, to='repository.ResultEdu', verbose_name='Образовательный результат'),
        ),
        migrations.AddField(
            model_name='digitalresource',
            name='subjects_tags',
            field=models.ManyToManyField(blank=True, to='repository.SubjectTag', verbose_name='Тэги дисциплин ЭОР'),
        ),
        migrations.AddField(
            model_name='conformitytheme',
            name='providing_discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.providingdiscipline', verbose_name='Рекомендация ЭОР в качестве обеспечения дисциплины'),
        ),
        migrations.AddField(
            model_name='conformitytheme',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.subjecttheme', verbose_name='Тема дисциплины'),
        ),
    ]
