# Generated by Django 3.0.7 on 2020-09-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digitalresource',
            options={'ordering': ['title'], 'verbose_name': 'Паспорт ЦОР', 'verbose_name_plural': 'Паспорта ЦОР'},
        ),
        migrations.AlterField(
            model_name='eduprogram',
            name='title',
            field=models.CharField(max_length=450, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='source',
            name='URL',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
    ]
