# Generated by Django 3.0.7 on 2020-09-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20200929_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Наименование'),
        ),
    ]
