# Generated by Django 3.2.16 on 2022-11-02 17:12

from django.db import migrations, models
import django.db.models.deletion
import polymorphic.showfields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('repository', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduProgramSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_repository.eduprogramsubject_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'дисциплина/образовательная программа',
                'verbose_name_plural': 'дисциплины/образовательные программы',
            },
            bases=(polymorphic.showfields.ShowFieldType, models.Model),
        ),
        migrations.AlterField(
            model_name='direction',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Наименование'),
        ),
        migrations.CreateModel(
            name='SubjectChild',
            fields=[
                ('eduprogramsubject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='repository.eduprogramsubject')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.subject', verbose_name='дисциплина')),
            ],
            options={
                'verbose_name': 'дисциплина',
                'verbose_name_plural': 'дисциплины',
            },
            bases=('repository.eduprogramsubject',),
        ),
        migrations.CreateModel(
            name='EduProgramChild',
            fields=[
                ('eduprogramsubject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='repository.eduprogramsubject')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.eduprogram', verbose_name='образовательная программа')),
            ],
            options={
                'verbose_name': 'образовательная программа',
                'verbose_name_plural': 'образовательные программы',
            },
            bases=('repository.eduprogramsubject',),
        ),
    ]
