# Generated by Django 3.1.4 on 2021-03-12 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('repository', '0002_auto_20210310_1652'),
    ]

    operations = [

        migrations.AddField(
            model_name='digitalresource',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='authors_digital_resource', to='users.Person', verbose_name='Авторы'),
        ),
        migrations.AddField(
            model_name='digitalresource',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_digital_resource', to='users.person', verbose_name='Владелец'),
        ),
        migrations.CreateModel(
            name='ScientificBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('title', models.CharField(max_length=64, verbose_name='Наименование')),
                ('code', models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'научная отрасль',
                'verbose_name_plural': 'научные отрасли',
            },
        ),
        migrations.AlterField(
            model_name='digitalresource',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='eduprogram',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contacts',
            field=models.TextField(blank=True, null=True, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='contacts',
            field=models.TextField(blank=True, null=True, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='resultedu',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='subjecttheme',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='direction',
            name='scientific_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='repository.scientificbranch', verbose_name='Научная отрасль'),
        ),
    ]
