# Generated by Django 4.2.3 on 2023-07-13 01:38

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookmarkdigitalresource",
            options={"base_manager_name": "prefetch_manager"},
        ),
        migrations.AlterModelOptions(
            name="competence",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "компетенция",
                "verbose_name_plural": "компетенции",
            },
        ),
        migrations.AlterModelOptions(
            name="digitalresource",
            options={
                "base_manager_name": "prefetch_manager",
                "ordering": ["title"],
                "verbose_name": "паспорт ЭОР",
                "verbose_name_plural": "паспорта ЭОР",
            },
        ),
        migrations.AlterModelOptions(
            name="direction",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "направление подготовки",
                "verbose_name_plural": "направления подготовки",
            },
        ),
        migrations.AlterModelOptions(
            name="directionsenlargedgroup",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "укрупненная группа направлений",
                "verbose_name_plural": "укрупненные группа направлений",
            },
        ),
        migrations.AlterModelOptions(
            name="eduprogram",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "образовательная программа",
                "verbose_name_plural": "образовательные программы",
            },
        ),
        migrations.AlterModelOptions(
            name="eduprogramtag",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "тег образовательной программы",
                "verbose_name_plural": "теги образовательных программ",
            },
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "организация",
                "verbose_name_plural": "организации",
            },
        ),
        migrations.AlterModelOptions(
            name="platform",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "платформа",
                "verbose_name_plural": "платформы",
            },
        ),
        migrations.AlterModelOptions(
            name="resultedu",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "образовательный результат",
                "verbose_name_plural": "образовательные результаты",
            },
        ),
        migrations.AlterModelOptions(
            name="scientificbranch",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "научная отрасль",
                "verbose_name_plural": "научные отрасли",
            },
        ),
        migrations.AlterModelOptions(
            name="source",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "компонент",
                "verbose_name_plural": "компоненты",
            },
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "дисциплина",
                "verbose_name_plural": "дисциплины",
            },
        ),
        migrations.AlterModelOptions(
            name="subjecttag",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "тег дисциплины",
                "verbose_name_plural": "теги дисциплин",
            },
        ),
        migrations.AlterModelManagers(
            name="bookmarkdigitalresource",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
