# Generated by Django 3.0.7 on 2020-12-22 11:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20200929_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('code', models.CharField(max_length=8, verbose_name='Код направления')),
            ],
            options={
                'verbose_name': 'Направление подготовки',
                'verbose_name_plural': 'Направления подготовки',
            },
        ),
        migrations.AlterField(
            model_name='conformitytheme',
            name='providing_discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.ProvidingDiscipline', verbose_name='Рекомендация ЭОР в качестве обеспечения дисциплины'),
        ),
        migrations.AlterField(
            model_name='digitalresource',
            name='conformity_theme',
            field=models.ManyToManyField(blank=True, to='repository.ConformityTheme', verbose_name='Соответствие ЭОР темам дисциплины'),
        ),
        migrations.AlterField(
            model_name='digitalresource',
            name='edu_programs_tags',
            field=models.ManyToManyField(blank=True, to='repository.EduProgramTag', verbose_name='Тэги образовательных программ ЭОР'),
        ),
        migrations.AlterField(
            model_name='digitalresource',
            name='provided_disciplines',
            field=models.ManyToManyField(blank=True, to='repository.ProvidingDiscipline', verbose_name='ЭОР рекомендован в качестве обеспечения дисциплины'),
        ),
        migrations.AlterField(
            model_name='digitalresource',
            name='subjects_tags',
            field=models.ManyToManyField(blank=True, to='repository.SubjectTag', verbose_name='Тэги дисциплин ЭОР'),
        ),
        migrations.AlterField(
            model_name='drstatus',
            name='digital_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.DigitalResource', verbose_name='Паспорт ЭОР'),
        ),
        migrations.AlterField(
            model_name='source',
            name='digital_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.DigitalResource', verbose_name='Паспорт ЭОР'),
        ),
        migrations.DeleteModel(
            name='WorkPlanAcademicGroup',
        ),
    ]
