# Generated by Django 3.1.4 on 2021-03-12 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20210312_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduprogram',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='repository.direction', verbose_name='Направление подготовки'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='scientific_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='repository.scientificbranch', verbose_name='Научная отрасль'),
        ),
    ]
