# Generated by Django 3.1.4 on 2021-03-12 12:38

import uuid

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('repository', '0004_auto_20210312_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionsEnlargedGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('title', models.CharField(max_length=128, verbose_name='Наименование УГН')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Код УГН')),
            ],
            options={
                'verbose_name': 'укрупненная группа направлений',
                'verbose_name_plural': 'укрупненные группа направлений',
            },
        ),
        migrations.AddField(
            model_name='eduprogram',
            name='_cipher',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Шифр ОП'),
        ),
        migrations.AddField(
            model_name='eduprogram',
            name='admission_years',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(blank=True, null=True), null=True, size=None),
        ),
        migrations.AddField(
            model_name='eduprogram',
            name='approve_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год утверждения'),
        ),
        migrations.AddField(
            model_name='eduprogram',
            name='edu_level',
            field=models.CharField(blank=True, choices=[('0', 'бакалавриат'), ('1', 'прикладной бакалавриат'),
                                                        ('2', 'магистратура'), ('3', 'аспирантура'),
                                                        ('4', 'специалитет')], max_length=1, null=True,
                                   verbose_name='Уровень подготовки'),
        ),
        migrations.AddField(
            model_name='eduprogram',
            name='head',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Руководитель'),
        ),
        migrations.AddField(
            model_name='eduprogram',
            name='site_admin',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Администратор сайта ОП'),
        ),
        migrations.AddField(
            model_name='eduprogram',
            name='standard',
            field=models.CharField(blank=True,
                                   choices=[('SUOS', 'СУОС'), ('FGOS3++', 'ФГОС 3++'), ('FGOS VO', 'ФГОС ВО')],
                                   max_length=9, null=True, verbose_name='Стандарт'),
        ),
    ]
