# Generated by Django 3.1.4 on 2021-04-21 04:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('repository', '0007_auto_20210419_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'Компонент', 'verbose_name_plural': 'Компоненты'},
        ),
    ]
