# Generated by Django 3.1.4 on 2021-04-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_auto_20210421_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(blank=True, choices=[('URL', 'url'), ('FILE', 'Файл')], max_length=150, null=True, verbose_name='Тип'),
        ),
    ]
