# Generated by Django 3.1.4 on 2021-04-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0012_merge_20210430_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalresource',
            name='competences',
            field=models.ManyToManyField(blank=True, to='repository.Competence', verbose_name='Компетенции'),
        ),
    ]
