# Generated by Django 3.1.10 on 2021-05-13 19:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repository', '0013_digitalresource_competences'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkDigitalResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.digitalresource', verbose_name='Паспорт ЭОР')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'db_table': 'bookmark__digital_resource',
            },
        ),
    ]
