# Generated by Django 3.1.10 on 2021-06-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0014_bookmarkdigitalresource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eduprogramtag',
            options={'verbose_name': 'Тег образовательной программы', 'verbose_name_plural': 'Теги образовательных программ'},
        ),
        migrations.AlterModelOptions(
            name='subjecttag',
            options={'verbose_name': 'Тег дисциплины', 'verbose_name_plural': 'Теги дисциплин'},
        ),
        migrations.AlterField(
            model_name='digitalresource',
            name='edu_programs_tags',
            field=models.ManyToManyField(blank=True, to='repository.EduProgramTag', verbose_name='Теги направлений подготвоки / Образовательных программ ЭОР'),
        ),
        migrations.AlterField(
            model_name='digitalresource',
            name='subjects_tags',
            field=models.ManyToManyField(blank=True, to='repository.SubjectTag', verbose_name='Теги дисциплин ЭОР'),
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(blank=True, choices=[('URL', 'URL'), ('FILE', 'Файл')], max_length=150, null=True, verbose_name='Тип'),
        ),
    ]
