# Generated by Django 3.1.12 on 2021-07-26 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0016_auto_20210514_0840'),
        ('repository', '0015_auto_20210619_2214'),
    ]

    operations = [
    ]
