# Generated by Django 3.1.12 on 2021-06-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0015_auto_20210619_2214'),
        ('repository', '0016_auto_20210514_0840'),
    ]

    operations = [
    ]
