# Generated by Django 3.1.12 on 2021-06-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0017_merge_20210627_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencegroup',
            name='name',
            field=models.CharField(max_length=400, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='digitalresource',
            name='edu_programs_tags',
            field=models.ManyToManyField(blank=True, to='repository.EduProgramTag', verbose_name='Теги образовательных программ ЭОР'),
        ),
        migrations.AlterField(
            model_name='digitalresource',
            name='title',
            field=models.CharField(max_length=1024, verbose_name='Наименование ресурса'),
        ),
        migrations.AlterField(
            model_name='language',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(blank=True, choices=[('URL', 'Ссылочный'), ('FILE', 'Файл')], max_length=150, null=True, verbose_name='Тип'),
        ),
    ]
