# Generated by Django 3.1.12 on 2021-07-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0017_merge_20210726_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencegroup',
            name='name',
            field=models.CharField(max_length=400, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='digitalresource',
            name='edu_programs_tags',
            field=models.ManyToManyField(blank=True, to='repository.EduProgramTag', verbose_name='Тэги образовательных программ ЭОР'),
        ),
        migrations.AlterField(
            model_name='digitalresource',
            name='subjects_tags',
            field=models.ManyToManyField(blank=True, to='repository.SubjectTag', verbose_name='Тэги дисциплин ЭОР'),
        ),
        migrations.AlterField(
            model_name='digitalresource',
            name='title',
            field=models.CharField(max_length=1024, verbose_name='Наименование ресурса'),
        ),
        migrations.AlterField(
            model_name='language',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(blank=True, choices=[('URL', 'Ссылочный'), ('FILE', 'Файл')], max_length=150, null=True, verbose_name='Тип'),
        ),
    ]
