# Generated by Django 3.1.12 on 2021-08-22 17:40

import auto_prefetch
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0023_student_academic_group'),
        ('repository', '0019_merge_20210822_0855'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='competence',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='digitalresource',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='direction',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='directionsenlargedgroup',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='eduprogram',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='eduprogramtag',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='organization',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='platform',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='resultedu',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='scientificbranch',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='source',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='subject',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='subjecttag',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='bookmarkdigitalresource',
            name='obj',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.digitalresource', verbose_name='Паспорт ЭОР'),
        ),
        migrations.AlterField(
            model_name='bookmarkdigitalresource',
            name='user',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='digitalresource',
            name='copyright_holder',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='repository.organization', verbose_name='Правообладатель'),
        ),
        migrations.AlterField(
            model_name='digitalresource',
            name='language',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='repository.language', verbose_name='Язык ресурса'),
        ),
        migrations.AlterField(
            model_name='digitalresource',
            name='owner',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_digital_resource', to='users.person', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='digitalresource',
            name='platform',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='repository.platform', verbose_name='Платформа'),
        ),
        migrations.AlterField(
            model_name='digitalresource',
            name='subjects_tags',
            field=models.ManyToManyField(blank=True, to='repository.SubjectTag', verbose_name='Теги дисциплин ЭОР'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='scientific_branch',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='repository.scientificbranch', verbose_name='Научная отрасль'),
        ),
        migrations.AlterField(
            model_name='eduprogram',
            name='direction',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='repository.direction', verbose_name='Направление подготовки'),
        ),
        migrations.AlterField(
            model_name='eduprogramtag',
            name='tag',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.eduprogram', verbose_name='Образовательная программа'),
        ),
        migrations.AlterField(
            model_name='resultedu',
            name='competence',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='repository.competence', verbose_name='Компетенция'),
        ),
        migrations.AlterField(
            model_name='source',
            name='digital_resource',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.digitalresource', verbose_name='Паспорт ЭОР'),
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(blank=True, choices=[('URL', 'URL'), ('FILE', 'Файл')], max_length=150, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='subjecttag',
            name='tag',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.subject', verbose_name='Дисциплина'),
        ),
    ]
