# Generated by Django 3.2.6 on 2021-09-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0020_auto_20210822_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='link_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('URL', 'URL'), ('FILE', 'Файл')], max_length=8, verbose_name='Тип'),
        ),
    ]
