# Generated by Django 3.2.6 on 2021-09-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0021_auto_20210907_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('URL', 'URL'), ('FILE', 'Файл')], max_length=8, null=True, verbose_name='Тип'),
        ),
    ]
