# Generated by Django 3.2.8 on 2021-10-18 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0022_alter_source_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competence',
            options={'verbose_name': 'компетенция', 'verbose_name_plural': 'компетенции'},
        ),
        migrations.AlterModelOptions(
            name='digitalresource',
            options={'ordering': ['title'], 'verbose_name': 'паспорт ЭОР', 'verbose_name_plural': 'паспорта ЭОР'},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'verbose_name': 'направление подготовки', 'verbose_name_plural': 'направления подготовки'},
        ),
        migrations.AlterModelOptions(
            name='eduprogram',
            options={'verbose_name': 'образовательная программа', 'verbose_name_plural': 'образовательные программы'},
        ),
        migrations.AlterModelOptions(
            name='eduprogramtag',
            options={'verbose_name': 'тег образовательной программы', 'verbose_name_plural': 'теги образовательных программ'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'язык ресура', 'verbose_name_plural': 'языки ресурсов'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'организация', 'verbose_name_plural': 'организации'},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'verbose_name': 'платформа', 'verbose_name_plural': 'платформы'},
        ),
        migrations.AlterModelOptions(
            name='resultedu',
            options={'verbose_name': 'образовательный результат', 'verbose_name_plural': 'образовательные результаты'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'компонент', 'verbose_name_plural': 'компоненты'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'дисциплина', 'verbose_name_plural': 'дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='subjecttag',
            options={'verbose_name': 'тег дисциплины', 'verbose_name_plural': 'теги дисциплин'},
        ),
    ]
