# Generated by Django 3.2.13 on 2022-06-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0023_auto_20211018_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='link_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Наименование'),
        ),
    ]
