# Generated by Django 3.2.13 on 2022-06-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0024_alter_source_link_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='title',
            field=models.TextField(verbose_name='Наименование'),
        ),
    ]
