# Generated by Django 3.1.4 on 2021-03-23 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20200609_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='survey.survey', verbose_name='Survey'),
        ),
    ]
