# Generated by Django 3.1.4 on 2021-04-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_response_expertise_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'get_latest_by': 'created', 'verbose_name': 'Set of answers to surveys', 'verbose_name_plural': 'Sets of answers to surveys'},
        ),
    ]
