# Generated by Django 3.2.6 on 2021-09-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_remove_question_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='per_discipline',
            field=models.BooleanField(default=False, verbose_name='Для каждой дисциплины'),
        ),
    ]
