# Generated by Django 3.2.6 on 2021-09-10 11:14

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0021_auto_20210907_1444'),
        ('survey', '0020_question_per_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='discipline',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.subject', verbose_name='Дисциплина'),
        ),
    ]
