# Generated by Django 3.1.4 on 2021-03-10 11:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complexes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('type', models.CharField(choices=[('METHODIGAL', 'Методическая'), ('CONTENT', 'Содержательная'), ('TECH', 'Техническая'), ('NO_TYPE', 'Отсутствует тип экспертизы')], default='NO_TYPE', max_length=30, verbose_name='Тип чек-листа')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения экспертизы')),
                ('protocol', models.CharField(max_length=424, verbose_name='№ Протокола учебно-методического совета института')),
                ('status', models.CharField(blank=True, choices=[('START', 'Назначена'), ('IN_PROCESS', 'В процессе'), ('END', 'Завершена')], default='START', max_length=30, verbose_name='Состояние')),
            ],
            options={
                'verbose_name': 'Чек-лист экспертизы',
                'verbose_name_plural': 'Чек-листы экспертиз',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('title', models.CharField(max_length=300, verbose_name='Показатель')),
                ('answer', models.CharField(blank=True, choices=[('HIGH', 'Высокая'), ('HIGH_NORM', 'Выше среднего'), ('NORM', 'Средняя'), ('LOW_NORM', 'Ниже среднего'), ('LOW', 'Низкая'), ('DO_NOT_MATCH', 'Не соответствует')], max_length=30, verbose_name='Тип чек-листа')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.checklist', verbose_name='Чек-лист эеспертизы')),
            ],
            options={
                'verbose_name': 'Чек-лист экспертизы',
                'verbose_name_plural': 'Чек-листы экспертиз',
            },
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата заявки')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='До какого действует статус экспертизы')),
                ('file', models.FileField(blank=True, null=True, upload_to='upload/files', verbose_name='№ протокола комиссии по ресурсному обеспечению модулей и ЭО методического совета')),
                ('remarks', models.TextField(blank=True, verbose_name='Замечания и рекомендации комиссии')),
                ('status', models.CharField(choices=[('SUB_APP', 'подана заявка'), ('ON_EXPERTISE', 'на экспертизе'), ('ON_REVISION', 'на доработку'), ('ASSIGNED_STATUS', 'присвоен статус'), ('NOT_ASSIGNED_STATUS', 'не присвоен статус')], default='NOT_ASSIGNED_STATUS', max_length=30, verbose_name='Состояние экспертизы')),
                ('type', models.CharField(blank=True, choices=[('FULL', 'Полная'), ('COMPLIANCE_DISCIPLINE', 'На соответствие дисциплине')], max_length=30, null=True, verbose_name='Тип экспертизы')),
                ('quality_category', models.CharField(blank=True, choices=[('INNER', 'внутренний'), ('OUTER', 'внешний'), ('OUTSIDE', 'сторонний')], max_length=30, verbose_name='Категория качества')),
                ('interactive_category', models.CharField(blank=True, choices=[('NOT_INTERACTIVE', 'не интерактивный'), ('WITH_TEACHER_SUPPORT', 'с поддержкой преподавателя'), ('AUTO', 'автоматизированный')], max_length=30, verbose_name='Категория интерактивности')),
                ('digital_complexes', models.ManyToManyField(blank=True, to='complexes.DigitalComplex', verbose_name='ЭУМК')),
            ],
            options={
                'verbose_name': 'Экспертиза',
                'verbose_name_plural': 'Экспертизы',
            },
        ),
    ]
