# Generated by Django 3.1.4 on 2021-01-25 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
        ('repository', '0001_initial'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertise',
            name='digital_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.digitalresource', verbose_name='Паспорт ЭОР'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='directions',
            field=models.ManyToManyField(blank=True, to='repository.Direction', verbose_name='Направление подготовки'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='expert',
            field=models.ManyToManyField(blank=True, to='users.Expert', verbose_name='Назначенные эксперты'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_expertise', to='users.person', verbose_name='Инициатор'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='repository.Subject', verbose_name='Дисциплина(ы)'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='expert',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.expert', verbose_name='Эксперт'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='expertise',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inspections.expertise', verbose_name='Экспертиза'),
        ),
    ]
