# Generated by Django 4.1.7 on 2023-03-15 18:42

import auto_prefetch
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("complexes", "0002_initial"),
        ("repository", "0001_initial"),
        ("inspections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="summaryindicator",
            name="edu_program_subject",
            field=models.ManyToManyField(
                to="repository.eduprogramsubject",
                verbose_name="дисциплина/образовательная программа",
            ),
        ),
        migrations.AddField(
            model_name="summaryindicator",
            name="expertise_request",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="inspections.expertiserequest",
                verbose_name="Заявка",
            ),
        ),
        migrations.AddField(
            model_name="summaryindicator",
            name="indicator",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inspections.indicator",
                verbose_name="Показатель",
            ),
        ),
        migrations.AddField(
            model_name="statusrequirement",
            name="indicator",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inspections.indicator",
                verbose_name="Показатель",
            ),
        ),
        migrations.AddField(
            model_name="statusrequirement",
            name="status",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirements",
                to="inspections.status",
            ),
        ),
        migrations.AddField(
            model_name="opinionindicator",
            name="acceptable_indicator_value",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opinion_indicators",
                to="inspections.acceptableindicatorvalue",
                verbose_name="Значение показателя",
            ),
        ),
        migrations.AddField(
            model_name="opinionindicator",
            name="discipline",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="repository.subject",
                verbose_name="Дисциплина",
            ),
        ),
        migrations.AddField(
            model_name="opinionindicator",
            name="expertise_opinion",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opinion_indicators",
                to="inspections.expertiseopinion",
                verbose_name="Экспертное заключение",
            ),
        ),
        migrations.AddField(
            model_name="opinionindicator",
            name="indicator",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opinion_indicators",
                to="inspections.indicator",
                verbose_name="Показатель",
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="category",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="indicators",
                to="inspections.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="discipline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="repository.subject",
                verbose_name="Дисциплина",
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="expertise_type",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indicators",
                to="inspections.expertisetype",
                verbose_name="Вид экспертизы",
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="parent",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to="inspections.indicator",
            ),
        ),
        migrations.AddField(
            model_name="expertiserequest",
            name="digital_complexes",
            field=models.ManyToManyField(
                blank=True, to="complexes.digitalcomplex", verbose_name="ЭУМК"
            ),
        ),
        migrations.AddField(
            model_name="expertiserequest",
            name="digital_resource",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="repository.digitalresource",
                verbose_name="Паспорт ЭОР",
            ),
        ),
        migrations.AddField(
            model_name="expertiserequest",
            name="directions",
            field=models.ManyToManyField(
                blank=True,
                to="repository.direction",
                verbose_name="Направление подготовки",
            ),
        ),
    ]
