# Generated by Django 3.2.16 on 2022-11-01 20:00

import auto_prefetch
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repository', '0001_initial'),
        ('complexes', '0002_initial'),
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinionindicator',
            name='discipline',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.subject', verbose_name='Дисциплина'),
        ),
        migrations.AddField(
            model_name='opinionindicator',
            name='expertise_opinion',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinion_indicators', to='inspections.expertiseopinion', verbose_name='Экспертное заключение'),
        ),
        migrations.AddField(
            model_name='opinionindicator',
            name='indicator',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinion_indicators', to='inspections.indicator', verbose_name='Показатель'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='category',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicators', to='inspections.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.subject', verbose_name='Дисциплина'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='expertise_type',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='inspections.expertisetype', verbose_name='Вид экспертизы'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='inspections.indicator'),
        ),
        migrations.AddField(
            model_name='expertiserequest',
            name='digital_complexes',
            field=models.ManyToManyField(blank=True, to='complexes.DigitalComplex', verbose_name='ЭУМК'),
        ),
        migrations.AddField(
            model_name='expertiserequest',
            name='digital_resource',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.digitalresource', verbose_name='Паспорт ЭОР'),
        ),
        migrations.AddField(
            model_name='expertiserequest',
            name='directions',
            field=models.ManyToManyField(blank=True, to='repository.Direction', verbose_name='Направление подготовки'),
        ),
    ]
