# Generated by Django 3.1.4 on 2021-03-10 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertise',
            name='digital_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.digitalresource',
                                    verbose_name='Паспорт ЭОР'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='directions',
            field=models.ManyToManyField(blank=True, to='repository.Direction', verbose_name='Направление подготовки'),
        ),
    ]
