# Generated by Django 3.2.16 on 2022-11-01 20:00

import auto_prefetch
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('repository', '0001_initial'),
        ('inspections', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertiserequest',
            name='expert',
            field=models.ManyToManyField(blank=True, to='users.Expert', verbose_name='Назначенные эксперты'),
        ),
        migrations.AddField(
            model_name='expertiserequest',
            name='owner',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_expertise', to='users.person', verbose_name='Инициатор'),
        ),
        migrations.AddField(
            model_name='expertiserequest',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='repository.Subject', verbose_name='Дисциплина(ы)'),
        ),
        migrations.AddField(
            model_name='expertiseopinion',
            name='expert',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.expert', verbose_name='Эксперт'),
        ),
        migrations.AddField(
            model_name='expertiseopinion',
            name='expertise_request',
            field=auto_prefetch.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inspections.expertiserequest', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='expertiseopinion',
            name='expertise_type',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opinions', to='inspections.expertisetype', verbose_name='Вид экспертизы'),
        ),
        migrations.AddField(
            model_name='category',
            name='expertise_type',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='inspections.expertisetype', verbose_name='Вид экспертизы'),
        ),
        migrations.AddField(
            model_name='acceptableindicatorvalue',
            name='indicator',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.indicator', verbose_name='Показатель'),
        ),
    ]
