# Generated by Django 3.1.4 on 2021-02-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_auto_20210204_1324'),
        ('inspections', '0002_auto_20210126_0347'),
    ]

    operations = [
    ]
