# Generated by Django 3.2.16 on 2022-11-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptableindicatorvalue',
            name='per_discipline',
        ),
    ]
