# Generated by Django 4.2.3 on 2023-07-13 01:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inspections", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acceptableindicatorvalue",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "допустимое значение показателя",
                "verbose_name_plural": "допустимые значения показателя",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.AlterModelOptions(
            name="expertiseopinion",
            options={
                "base_manager_name": "prefetch_manager",
                "get_latest_by": "date",
                "verbose_name": "экспертное заключение",
                "verbose_name_plural": "экспертные заключения",
            },
        ),
        migrations.AlterModelOptions(
            name="expertiserequest",
            options={
                "base_manager_name": "prefetch_manager",
                "get_latest_by": "date",
                "verbose_name": "заявка",
                "verbose_name_plural": "заявки",
            },
        ),
        migrations.AlterModelOptions(
            name="expertisetype",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "вид экспертизы",
                "verbose_name_plural": "виды экспертизы",
            },
        ),
        migrations.AlterModelOptions(
            name="indicator",
            options={
                "base_manager_name": "prefetch_manager",
                "ordering": ("expertise_type", "order"),
                "verbose_name": "показатель",
                "verbose_name_plural": "показатели",
            },
        ),
        migrations.AlterModelOptions(
            name="opinionindicator",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "показатель заключения",
                "verbose_name_plural": "показатели заключения",
            },
        ),
        migrations.AlterModelOptions(
            name="summaryindicator",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "сводный показатель",
                "verbose_name_plural": "сводные показатели",
            },
        ),
    ]
