# Generated by Django 3.1.4 on 2021-03-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_auto_20210311_1223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionBase',
        ),
    ]
