# Generated by Django 3.1.4 on 2021-03-12 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionBase',
        ),
    ]
