# Generated by Django 3.2.16 on 2022-11-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20221102_2212'),
        ('inspections', '0005_opinionindicator_acceptable_indicator_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryindicator',
            name='edu_program_subject',
            field=models.ManyToManyField(to='repository.EduProgramSubject', verbose_name='дисциплина/образовательная программа'),
        ),
    ]
