# Generated by Django 3.1.4 on 2021-03-24 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_auto_20210324_1426'),
        ('inspections', '0006_auto_20210316_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertiserequest',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='survey.survey', verbose_name='Опросник'),
        ),
    ]
