# Generated by Django 3.1.4 on 2021-03-24 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='expertiserequest',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='survey.survey', verbose_name='Опросник'),
        ),
    ]
