# Generated by Django 3.1.4 on 2021-04-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок действия статуса экспертизы'),
        ),
    ]
