# Generated by Django 3.1.4 on 2021-04-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='expertiserequest',
            name='status',
            field=models.CharField(blank=True, choices=[('START', 'В процессе'), ('IN_PROCESS', 'В процессе'),
                                                        ('END', 'Завершена')], default='START', max_length=30,
                                   verbose_name='Состояние'),
        ),
    ]
