# Generated by Django 3.1.4 on 2021-04-29 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='expertiserequest',
            name='checklist',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='CheckListQestion',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
