# Generated by Django 3.1.10 on 2021-05-12 02:36

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inspections', '0010_auto_20210429_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(
                    choices=[(0, 'Кадровый состав авторского коллектива (Соблюдение квалификационных требований)'),
                             (1, 'Полнота заполнения полей паспорта ресурса'),
                             (2, 'Редакционно-издательская обработка'),
                             (3, 'Соблюдение требований в области защиты авторских прав'),
                             (4, 'Соответствие требованиям к оценочным материалам'),
                             (5, 'Состав применяемых технологий'), (6, 'Управление учебной деятельностью'),
                             (7, 'Соблюдение требований в области защиты авторских прав'),
                             (8, 'Соответствие требованиям к оценочным материалам'),
                             (9, 'Соответствие содержанию дисциплины ОП'), (10, 'Соответствие требованиям к контенту'),
                             (11, 'Дизайн-эргономические и технические характеристики используемых средств обучения'),
                             (12, 'Доступ к ресурсу')], default='qual', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=1024)),
                ('group', models.CharField(choices=[('qual', 'Категория качества контента ЭОР'), (
                'struct', 'Соответствие структуры и содержания ЭОР требованиям конкретных дисциплин ОП'), ('tech',
                                                                                                           'Технологические возможности и сценарии функционирования ЭОР')],
                                           default='qual', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=1024)),
                ('values',
                 django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=None)),
                ('group',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.indicatorgroup')),
            ],
        ),
    ]
