# Generated by Django 3.1.10 on 2021-05-12 06:35

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inspections', '0013_auto_20210512_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='values',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=32),
                                                                          blank=True, default=list, size=None),
        ),
    ]
