# Generated by Django 3.1.10 on 2021-05-12 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inspections', '0014_auto_20210512_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.survey'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='title',
            field=models.CharField(db_index=True, max_length=1024, unique=True),
        ),
    ]
