# Generated by Django 3.1.10 on 2021-05-12 11:30

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0015_auto_20210512_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='values',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='indicatorgroup',
            name='title',
            field=models.CharField(choices=[('0', 'Кадровый состав авторского коллектива (Соблюдение квалификационных требований)'), ('1', 'Полнота заполнения полей паспорта ресурса'), ('2', 'Редакционно-издательская обработка'), ('3', 'Соблюдение требований в области защиты авторских прав'), ('4', 'Соответствие требованиям к оценочным материалам'), ('5', 'Состав применяемых технологий'), ('6', 'Управление учебной деятельностью'), ('7', 'Соблюдение требований в области защиты авторских прав'), ('8', 'Соответствие требованиям к оценочным материалам'), ('9', 'Соответствие содержанию дисциплины ОП'), ('10', 'Соответствие требованиям к контенту'), ('11', 'Дизайн-эргономические и технические характеристики используемых средств обучения'), ('12', 'Доступ к ресурсу'), ('13', 'Соответствие требованиям к структуре ресурса')], default='qual', max_length=1024, unique=True),
        ),
    ]
