# Generated by Django 3.1.10 on 2021-05-12 11:34

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0017_auto_20210512_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='values',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32, null=True), blank=True, null=True, size=None),
        ),
    ]
