# Generated by Django 3.1.12 on 2021-07-26 09:35

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={'ordering': ['order'], 'verbose_name': 'Показатель', 'verbose_name_plural': 'Показатели'},
        ),
        migrations.AlterModelOptions(
            name='indicatorgroup',
            options={'verbose_name': 'Группа показателей', 'verbose_name_plural': 'Группы показателей'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),

        # migrations.AddField(
        #     model_name='indicator',
        #     name='per_discipline',
        #     field=models.BooleanField(default=False, verbose_name='Для каждой дисциплины'),
        # ),
        migrations.AlterField(
            model_name='status',
            name='group',
            field=models.CharField(choices=[('qual', 'Категория качества контента ЭОР'), ('struct', 'Соответствие структуры и содержания ЭОР требованиям конкретных дисциплин ОП'), ('tech', 'Технологические возможности и сценарии функционирования ЭОР')], default='qual', max_length=6, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='status',
            name='title',
            field=models.CharField(db_index=True, max_length=1024, verbose_name='Наименование'),
        ),
        # migrations.CreateModel(
        #     name='StatusRequirement',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('allowed_values', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32, null=True), blank=True, null=True, size=None, verbose_name='Допустимые значения')),
        #         ('allowed_num_values', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True, verbose_name='Диапазон допустимых числовых значений')),
        #         ('exclude_values', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32, null=True), blank=True, null=True, size=None, verbose_name='Исключаемые значения')),
        #         ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.indicator', verbose_name='Показатель')),
        #         ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.status')),
        #     ],
        # ),
    ]
