# Generated by Django 3.1.10 on 2021-05-14 03:28

import django.db.models.deletion
import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inspections', '0021_indicator_per_discipline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={'verbose_name': 'Показатель', 'verbose_name_plural': 'Показатели'},
        ),
        migrations.AlterModelOptions(
            name='indicatorgroup',
            options={'verbose_name': 'Группа показателей', 'verbose_name_plural': 'Группы показателей'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.CreateModel(
            name='StatusRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_values', django_better_admin_arrayfield.models.fields.ArrayField(
                    base_field=models.CharField(blank=True, max_length=32, null=True), blank=True, null=True,
                    size=None)),
                ('allowed_num_values', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.indicator',
                                                verbose_name='Показатель')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.status')),
            ],
        ),
    ]
