# Generated by Django 3.1.10 on 2021-05-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0022_auto_20210514_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={'ordering': ['order'], 'verbose_name': 'Показатель', 'verbose_name_plural': 'Показатели'},
        ),
        migrations.AddField(
            model_name='indicator',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
