# Generated by Django 3.1.10 on 2021-05-14 05:33

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='exclude_values',
        ),
        migrations.AddField(
            model_name='statusrequirement',
            name='exclude_values',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32, null=True), blank=True, null=True, size=None),
        ),
    ]
