# Generated by Django 3.1.10 on 2021-05-14 09:17

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0026_auto_20210514_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorgroup',
            name='css_class',
        ),
        # migrations.AlterField(
        #     model_name='statusrequirement',
        #     name='allowed_num_values',
        #     field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True),
        # ),
    ]
