# Generated by Django 3.1.10 on 2021-05-14 11:28

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='statusrequirement',
            name='allowed_num_values',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True, verbose_name='Диапазон допустимых числовых значений'),
        ),
        migrations.AlterField(
            model_name='statusrequirement',
            name='allowed_values',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32, null=True), blank=True, null=True, size=None, verbose_name='Допустимые значения'),
        ),
        migrations.AlterField(
            model_name='statusrequirement',
            name='exclude_values',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32, null=True), blank=True, null=True, size=None, verbose_name='Исключаемые значения'),
        ),
    ]
