# Generated by Django 3.1.12 on 2021-08-22 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0028_auto_20210514_1628'),
        ('inspections', '0022_temporarystatus'),
    ]

    operations = [
    ]
