# Generated by Django 3.1.12 on 2021-08-22 18:56

import auto_prefetch
from django.db import migrations
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_student_academic_group'),
        ('survey', '0019_remove_question_indicator'),
        ('repository', '0020_auto_20210822_2240'),
        ('inspections', '0030_auto_20210822_2240'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='indicator',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='indicator',
            name='question',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.question'),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='digital_resource',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.digitalresource', verbose_name='Паспорт ЭОР'),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='owner',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_expertise', to='users.person', verbose_name='Инициатор'),
        ),
        migrations.AlterField(
            model_name='expertiserequest',
            name='expert',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.expert', verbose_name='Эксперт'),
        ),
        migrations.AlterField(
            model_name='expertiserequest',
            name='expertise',
            field=auto_prefetch.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inspections.expertise', verbose_name='Экспертиза'),
        ),
        migrations.AlterField(
            model_name='expertiserequest',
            name='survey',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='survey.survey', verbose_name='Опросник'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='group',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.indicatorgroup'),
        ),
    ]
