# Generated by Django 3.1.12 on 2021-08-22 19:21

import auto_prefetch
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='question',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.question'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32, null=True), blank=True, null=True, size=2), blank=True, null=True, size=None),
        ),
    ]
