# Generated by Django 3.1.12 on 2021-08-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0033_auto_20210823_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='hstore_values',
        ),
        migrations.AddField(
            model_name='indicator',
            name='json_values',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
