# Generated by Django 3.2.6 on 2021-09-15 07:25

import auto_prefetch
from django.db import migrations
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusrequirement',
            options={'base_manager_name': 'prefetch_manager'},
        ),
        migrations.AlterModelManagers(
            name='statusrequirement',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='statusrequirement',
            name='indicator',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.indicator', verbose_name='Показатель'),
        ),
        migrations.AlterField(
            model_name='statusrequirement',
            name='status',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='inspections.status'),
        ),
    ]
