# Generated by Django 3.2.6 on 2021-09-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0037_auto_20210823_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertiserequest',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата проведения экспертизы'),
        ),
    ]
