# Generated by Django 3.2.8 on 2021-10-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarystatus',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Тело статуса'),
        ),
    ]
