# Generated by Django 3.2.8 on 2021-10-18 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertise',
            options={'verbose_name': 'экспертиза', 'verbose_name_plural': 'экспертизы'},
        ),
        migrations.AlterModelOptions(
            name='expertiserequest',
            options={'verbose_name': 'эаявка', 'verbose_name_plural': 'эаявка'},
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={'verbose_name': 'показатель', 'verbose_name_plural': 'показатели'},
        ),
        migrations.AlterModelOptions(
            name='indicatorgroup',
            options={'verbose_name': 'группа показателей', 'verbose_name_plural': 'группы показателей'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'статус', 'verbose_name_plural': 'статусы'},
        ),
        migrations.AlterModelOptions(
            name='temporarystatus',
            options={'verbose_name': 'временный статус', 'verbose_name_plural': 'временные статусы'},
        ),
    ]
