# Generated by Django 3.2.13 on 2022-06-14 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertiserequest',
            options={'verbose_name': 'заявка', 'verbose_name_plural': 'заявка'},
        ),
    ]
