# Generated by Django 3.2.16 on 2022-10-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0043_alter_expertiserequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertise',
            options={'verbose_name': 'заявка', 'verbose_name_plural': 'заявки'},
        ),
        migrations.AlterModelOptions(
            name='expertiserequest',
            options={'verbose_name': 'экспертное заключение', 'verbose_name_plural': 'экспертные заключения'},
        ),
        migrations.AlterModelOptions(
            name='indicatorgroup',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterField(
            model_name='expertise',
            name='status',
            field=models.CharField(choices=[('SUB_APP', 'подана заявка'), ('ON_EXPERTISE', 'на экспертизе'), ('ON_REVISION', 'на доработку'), ('ASSIGNED_STATUS', 'присвоен статус'), ('NOT_ASSIGNED_STATUS', 'не присвоен статус')], default='NOT_ASSIGNED_STATUS', max_length=30, verbose_name='Состояние заявки'),
        ),
        migrations.AlterField(
            model_name='expertiserequest',
            name='status',
            field=models.CharField(blank=True, choices=[('START', 'Начата'), ('IN_PROCESS', 'В процессе'), ('END', 'Завершена')], default='START', max_length=30, verbose_name='Состояние'),
        ),
    ]
