# Generated by Django 3.2.16 on 2022-10-26 02:20

import uuid

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0030_auto_20211018_2339'),
        ('complexes', '0040_complexparentcomponent_literarysourcescomponent_platformcomponent_resourcecomponent_traditionalsessi'),
        ('repository', '0025_alter_competence_title'),
        ('inspections', '0044_auto_20221026_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseOpinion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата проведения экспертизы')),
                ('protocol', models.CharField(blank=True, max_length=424, null=True, verbose_name='№ Протокола учебно-методического совета института')),
                ('status', models.CharField(blank=True, choices=[('START', 'Начата'), ('IN_PROCESS', 'В процессе'), ('END', 'Завершена')], default='START', max_length=30, verbose_name='Состояние')),
            ],
            options={
                'verbose_name': 'экспертное заключение',
                'verbose_name_plural': 'экспертные заключения',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='expertiserequest',
            name='expert',
        ),
        migrations.RemoveField(
            model_name='expertiserequest',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='expertiserequest',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='temporarystatus',
            name='expertise',
        ),

        migrations.RenameModel(
            old_name='Expertise',
            new_name='Request',
        ),
        migrations.AddField(
            model_name='temporarystatus',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspections.request', verbose_name='Заявка'),
        ),
    ]
