# Generated by Django 3.2.16 on 2022-10-26 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0047_auto_20221026_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertisetype',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='expertisetype',
            name='display_method',
        ),
        migrations.RemoveField(
            model_name='expertisetype',
            name='editable_answers',
        ),
        migrations.RemoveField(
            model_name='expertisetype',
            name='expire_date',
        ),
        migrations.RemoveField(
            model_name='expertisetype',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='expertisetype',
            name='need_logged_user',
        ),
        migrations.RemoveField(
            model_name='expertisetype',
            name='publish_date',
        ),
    ]
