# Generated by Django 3.2.16 on 2022-10-26 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0050_auto_20221026_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='inspections.indicator'),
        ),
    ]
