# Generated by Django 3.2.16 on 2022-10-31 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0040_complexparentcomponent_literarysourcescomponent_platformcomponent_resourcecomponent_traditionalsessi'),
        ('users', '0030_auto_20211018_2339'),
        ('repository', '0025_alter_competence_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='ExpertiseRequest',
        ),
        migrations.RenameField(
            model_name='expertiseopinion',
            old_name='request',
            new_name='expertise_request',
        ),
        migrations.RenameField(
            model_name='summaryindicator',
            old_name='request',
            new_name='expertise_request',
        ),
        migrations.RenameField(
            model_name='temporarystatus',
            old_name='request',
            new_name='expertise_request',
        ),
    ]
