# Generated by Django 3.0.7 on 2020-12-22 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('METHODIGAL', 'Методическая'), ('CONTENT', 'Содержательная'), ('TECH', 'Техническая')], max_length=30, verbose_name='Вид экспертизы')),
                ('subdivision', models.CharField(max_length=500, verbose_name='Подразделение/отрасль')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Person')),
            ],
            options={
                'verbose_name': 'Эксперт',
                'verbose_name_plural': 'Эксперты',
            },
        ),
    ]
