# Generated by Django 3.1.4 on 2021-03-12 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('repository', '0003_auto_20210312_1626'),
        ('users', '0001_initial'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='academicgroup',
        #     name='direction',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
        #                             related_name='direction_academic_group', to='repository.direction',
        #                             verbose_name='Образовательная программа/Направление подготовки'),
        # ),
    ]
