# Generated by Django 3.1.4 on 2021-03-16 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20210312_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.person',
                                    verbose_name='Пользователь'),
        ),
    ]
