# Generated by Django 3.1.4 on 2021-04-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_auto_20210316_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicesExpert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(
                    choices=[('METHODICAL', 'Методическая'), ('CONTENT', 'Содержательная'), ('TECH', 'Техническая')],
                    max_length=30, verbose_name='Вид экспертизы')),
            ],
        ),
        migrations.RemoveField(
            model_name='expert',
            name='type',
        ),
        migrations.AddField(
            model_name='expert',
            name='types',
            field=models.ManyToManyField(to='users.ChoicesExpert'),
        ),
    ]
