# Generated by Django 3.1.4 on 2021-04-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_auto_20210427_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choicesexpert',
            options={'verbose_name': 'Тип экспертизы', 'verbose_name_plural': 'Типы экспертиз'},
        ),
        migrations.AlterField(
            model_name='expert',
            name='types',
            field=models.ManyToManyField(blank=True, null=True, to='users.ChoicesExpert',
                                         verbose_name='Вид экспертизы'),
        ),
    ]
