# Generated by Django 3.1.4 on 2021-04-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_auto_20210428_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='types',
            field=models.ManyToManyField(blank=True, to='users.ChoicesExpert', verbose_name='Вид экспертизы'),
        ),
    ]
