# Generated by Django 3.1.10 on 2021-05-17 05:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0014_bookmarkdigitalresource'),
        ('users', '0006_auto_20210428_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDisciplines',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последние обновление')),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.academicgroup', verbose_name='Академическая группа')),
                ('subject', models.ManyToManyField(blank=True, to='repository.Subject', verbose_name='Дисциплина(ы)')),
            ],
            options={
                'verbose_name': 'Дисциплина группы',
                'verbose_name_plural': 'Дисциплины групп',
            },
        ),
    ]
