# Generated by Django 3.1.10 on 2021-05-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210517_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdisciplines',
            name='semestr',
            field=models.PositiveSmallIntegerField(blank=True, max_length=10, null=True, verbose_name='Семестр'),
        ),
    ]
