# Generated by Django 3.1.10 on 2021-05-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_groupdisciplines_semestr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdisciplines',
            name='semestr',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Семестр'),
        ),
    ]
