# Generated by Django 3.1.10 on 2021-06-21 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0015_auto_20210619_2214'),
        ('users', '0010_auto_20210518_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupdisciplines',
            name='subjects',
        ),
        migrations.AddField(
            model_name='groupdisciplines',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='repository.subject', verbose_name='Дисциплина(ы)'),
        ),
        migrations.AlterField(
            model_name='groupdisciplines',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.academicgroup', verbose_name='Академическая группа'),
        ),
    ]
