# Generated by Django 3.1.10 on 2021-06-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210621_0856'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='groupdisciplines',
        #     name='id',
        #     field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
    ]
