# Generated by Django 3.1.10 on 2021-06-21 04:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210621_0933'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='groupdisciplines',
        #     name='id',
        #     field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        # ),
    ]
