# Generated by Django 3.1.10 on 2021-06-21 04:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210621_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicgroup',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='academicgroup',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Последние обновление'),
        ),
        # migrations.AlterField(
        #     model_name='academicgroup',
        #     name='id',
        #     field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        # ),
    ]
