# Generated by Django 3.1.10 on 2021-06-21 04:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210621_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicgroup',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        # migrations.AlterField(
        #     model_name='academicgroup',
        #     name='id',
        #     field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
    ]
