# Generated by Django 3.1.10 on 2021-06-21 04:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210621_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicgroup',
            name='id',
        ),
        migrations.AlterField(
            model_name='academicgroup',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
