# Generated by Django 3.1.10 on 2021-06-21 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210621_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicgroup',
            old_name='uuid',
            new_name='id',
        ),
    ]
