# Generated by Django 3.1.10 on 2021-06-21 04:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210621_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicgroup',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
