# Generated by Django 3.1.10 on 2021-06-21 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210621_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupdisciplines',
            name='group',
        ),
    ]
