# Generated by Django 3.1.10 on 2021-06-21 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_groupdisciplines_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdisciplines',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.academicgroup', verbose_name='Академическая группа'),
        ),
    ]
