# Generated by Django 3.1.10 on 2021-06-21 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_groupdisciplines_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupdisciplines',
            old_name='group',
            new_name='academic_group',
        ),
    ]
