# Generated by Django 3.1.10 on 2021-06-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210621_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='academic_group',
        ),
    ]
