# Generated by Django 3.1.10 on 2021-06-23 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_student_academic_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.academicgroup', verbose_name='Номер академической группы'),
        ),
    ]
