# Generated by Django 3.2.6 on 2021-09-16 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('users', '0023_student_academic_group'), ('users', '0024_remove_academicgroup_direction'), ('users', '0025_remove_academicgroup_direction'), ('users', '0026_academicgroup_direction'), ('users', '0027_remove_academicgroup_direction'), ('users', '0028_academicgroup_direction'), ('users', '0029_remove_academicgroup_direction')]

    dependencies = [
        ('repository', '0022_alter_source_type'),
        ('users', '0022_remove_student_academic_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.academicgroup', verbose_name='Номер академической группы'),
        ),
    ]
