# Generated by Django 3.2.6 on 2021-09-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_academicgroup_direction'),
    ]

    operations = [

    ]
