# Generated by Django 3.2.6 on 2021-09-15 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_academicgroup_direction'),
    ]

    operations = [
    ]
