# Generated by Django 3.2.6 on 2021-09-15 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0022_alter_source_type'),
        ('users', '0027_remove_academicgroup_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicgroup',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='repository.direction'),
        ),
    ]
