# Generated by Django 3.2.6 on 2021-09-15 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_academicgroup_direction'),
    ]

    operations = [

    ]
