# Generated by Django 3.2.8 on 2021-10-18 18:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0029_remove_academicgroup_direction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicgroup',
            options={'verbose_name': 'академическая группа', 'verbose_name_plural': 'академические группы'},
        ),
        migrations.AlterModelOptions(
            name='choicesexpert',
            options={'verbose_name': 'тип экспертизы', 'verbose_name_plural': 'типы экспертиз'},
        ),
        migrations.AlterModelOptions(
            name='expert',
            options={'verbose_name': 'эксперт', 'verbose_name_plural': 'эксперты'},
        ),
        migrations.AlterModelOptions(
            name='groupdisciplines',
            options={'verbose_name': 'дисциплина группы', 'verbose_name_plural': 'дисциплины групп'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'профиль', 'verbose_name_plural': 'профили'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'студент', 'verbose_name_plural': 'студенты'},
        ),
    ]
